### ISSUE TITLE
Allow replacing default allocator functions

### ISSUE THREAD

**Issue by aviggiano** [RoaringBitmap/CRoaring#103]
I am writing a redis module called [redis-roaring](https://github.com/aviggiano/redis-roaring) that implements roaring bitmaps on top of redis.

The problem is that when I call `roaring_bitmap_create...` functions instead of Redis Modules API functions ([`RM_Alloc, RM_Calloc, RM_Realloc and RM_Free`](https://github.com/antirez/redis/blob/unstable/src/modules/API.md#rm_calloc)) my module's allocations are not automatically reported Redis, which leads to incorrect memory usage statistics (see issue [#3998](https://github.com/antirez/redis/issues/3998) on their repo).  

It would be nice if I could replace CRoaring's default allocators the same way the [sds](https://github.com/antirez/sds#using-a-different-allocator-for-sds) library does, by providing a header file to define macros for malloc, realloc and free.

Does this make sense? Would you be interested in a pull request?

**Comment by lemire** [comment]
I don't have a problem with this, but why can't you just redefine the following functions...

```
void* malloc(size_t sz);
int posix_memalign(void **memptr, size_t alignment, size_t size);
void * calloc(size_t count, size_t size);
void free(void *p);
void* realloc(void *p, size_t sz);
```

If you include a header that redefines these functions before including the roaring library, you ought to be in business, no?

For example, to track ``CRoaring`` memory usage, and make sure it is what it ought to be, I use the following header:  https://github.com/RoaringBitmap/CBitmapCompetition/blob/master/src/cmemcounter.h
(Don't use it in production!)

**Comment by aviggiano** [comment]
You are right, I can do this by my own using `dlsym`. Didn't thought about that.

In my opinion the header file is easier to modify and to integrate to existent projects, albeit less generic and less powerful, so I am not sure if it's worth the change. 

I guess I'll just close this issue for now. Thanks.

**Comment by lemire** [comment]
> In my opinion the header file is easier to modify and to integrate to existent projects, albeit less generic and less powerful, so I am not sure if it's worth the change.

Do get back to us if there is trouble.
