### ISSUE TITLE
Find N-th non existent element in a set

### ISSUE THREAD

**Issue by aviggiano** [RoaringBitmap/CRoaring#106]
[I am testing](https://github.com/aviggiano/redis-roaring/pull/24) CRoaring's bitmap operations against redis native bitmaps, and almost all functions seem equal to or better than their implementation performance-wise. 

The only operation that seems far behind is my version of the [`BITPOS`](https://redis.io/commands/bitpos) redis command. Since the original one returns the position of the first bit set to 1 or 0 in a string, the analogue is to return the first element in the set (when the `bit` parameter equals to 1) or the first non-existent element in the set (when `bit` equals to 0).

If I am not mistaken, the only way to find the N-th non existent element in a CRoaring bitmap is to invert it and to iterate over all elements until I find the N-th existent one. In redis' case, N always equals to 1. My functions are something like this:

```C
int64_t bitmap_get_nth_element_present(roaring_bitmap_t* bitmap, uint64_t n) {
  roaring_uint32_iterator_t* iterator = roaring_create_iterator(bitmap);
  int64_t element = -1;
  for (uint64_t i = 1; iterator->has_value; i++) {
    if (i == n) {
      element = iterator->current_value;
      break;
    }
    roaring_advance_uint32_iterator(iterator);
  }
  roaring_free_uint32_iterator(iterator);
  return element;
}

int64_t bitmap_get_nth_element_not_present(roaring_bitmap_t* bitmap, uint64_t n) {
  uint32_t last = roaring_bitmap_maximum(bitmaps);
  roaring_bitmap_t* inverted_bitmap = roaring_bitmap_flip(bitmap, 0, last + 1);
  int64_t element = bitmap_get_nth_element_present(inverted_bitmap, n);
  roaring_bitmap_free(inverted_bitmap);
  return element;
}
```

Am I doing anything wrong? Is there a better way to achieve this?

**Comment by gssiyankai** [comment]
I don't know what is the cost to flip a bitmap. If it is cheap, I believe it is ok.
IMO, you can use the same algorithm as the one to find the nth present element, except that you need to keep track of the previous present element so that you can infer how many elements set to 0 you jumped over.
HTH

**Comment by aviggiano** [comment]
Thank you for answering @gssiyankai, I believe your algorithm is better than flipping the bitmap. 
I will give it a try.

**Comment by lemire** [comment]
@aviggiano 

This is a valid issue, thanks for raising it. I think that @gssiyankai  has offered a good answer. I would make it stronger: I definitively think you want to avoid inverting the bitmap. This is a ``lazy`` approach that's convenient but unlikely to lead to good performance... I am not criticizing you... it is a fine way to do it if you want clear code that can be programmed quickly... but we can do a lot better.

What I suggest is that you try to implement what @gssiyankai  suggests. If you don't manage it, please get back to us... I think I can probably program it in 15 mins. 

Ultimately, we would like for the API to support this well.

In any case, we definitively want to get good performance on these queries and we are going to make sure it is the case.

Thanks again!

**Comment by aviggiano** [comment]
After implementing the algorithm described by @gssiyankai the `BITPOS` operation is faster on CRoaring than on redis native bitmaps, so I can close this issue now.

Thank you for helping.
