### ISSUE TITLE
In Place Serialization / Deserialization

### ISSUE THREAD

**Issue by davidwilcox** [RoaringBitmap/CRoaring#107]
It seems like the serialization and deserialization involve copying memory to and from the temporary buffer. This necessarily involves a copy. There's no way to serialize and deserialize in place so that no copies are needed? I'm looking for a way so that the data read from disk can be used in place without needing to copy into another data structure.

**Comment by lemire** [comment]
I think that what you are looking for is issue 74...

https://github.com/RoaringBitmap/CRoaring/issues/74
