### ISSUE TITLE
Implement in-place unions

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/CRoaring#11]
Currently we have working unions between roaring bitmaps, but not in-place unions.

**Comment by owenkaser** [comment]
I started work on this a while back, and today I am resuming it.

**Comment by lemire** [comment]
@owenkaser  Could we consider this issue resolved now as per https://github.com/RoaringBitmap/CRoaring/commit/b0e08fde480ed5e4152c9951cddc5b38fafe843b
?

I think that once something is in our testing routines, we no longer need an issue to remind us to work on it.

**Comment by lemire** [comment]
+1
