### ISSUE TITLE
Cannot compile amalgamation_demo.cpp on Visual Studio 2017

### ISSUE THREAD

**Issue by e-** [RoaringBitmap/CRoaring#115]
I tried to compile amalgamation_demo.cpp with amalgamated sources (i.e., roaring.h, .hh, and .c) on Visual Studio 2017 but the compiler gives me errors. I think most errors came from the fact that MSVC does not fully support C99 syntax such as designated initialization of structs (e.g., `rle16_t buffered = (rle16_t){.value = (uint16_t)0, .length = (uint16_t)0};`) Are there any instructions for running CRoaring on Visual Studio 2017?

**Comment by lemire** [comment]
We have detailed instructions on how to build under Visual Studio in the README:
 https://github.com/RoaringBitmap/CRoaring/blob/master/README.md#building-visual-studio-under-windows

Please reopen the issue only after taking into account these instructions.
