### ISSUE TITLE
Installing c++ headers (roaring64map.hh and roaring.hh)

### ISSUE THREAD

**Issue by kosloot** [RoaringBitmap/CRoaring#119]
I'm not a cmake expert, so maybe someone can give me a hint how to automatically install the C++ header files from the cpp directory to the default installation dir (/usr/local/include/roaring) ?
make doesn't do this, so I have to do this by hand now.

**Comment by lemire** [comment]
The latest commit should solve the problem, see...
https://github.com/RoaringBitmap/CRoaring/commit/7e0bb90521027b91d103fab73749fe288285649d

I'll close the issue as soon as you confirm the fix.

**Comment by kosloot** [comment]
Well....
it gets now installed in:
/usr/local/include/roaring/cpp/

Is this intentional?
I would expect the files to be in /usr/local/include/roaring/

(but could live with an extra cpp subdir)

**Comment by lemire** [comment]
It was deliberate, but it is trivial to change. I changed it in the last commit. Can you have a look?

I'll close as soon as you verify the fix.

**Comment by kosloot** [comment]
Yes, this works as expected.
Thanks for the quick responses.

**Comment by lemire** [comment]
Closing. I will issue a new release soon.
