### ISSUE TITLE
Conflict with Windows.h on VS 2017

### ISSUE THREAD

**Issue by e-** [RoaringBitmap/CRoaring#120]
Hello, 

To put in a nutshell, 

```cpp
#include <roaring.hh>

// ... example codes
```

works well on Windows 10, but

```cpp
#include <Windows.h>
#include <roaring.hh>

// ... example codes
```

gives me syntax errors: E0018	expected a ')'	in roaring.h.

I am using VS 2017 on Windows 10 and both are 64-bit. Do you have any workaround for this?

**Comment by madscientist** [comment]
I've experienced this a lot because Windows likes to #define various common things as macros, which then breaks other code.

If you invert the order of the includes (first roaring.hh then windows.h) does it work?  If so then that's definitely the problem.

If you can give more information (such as which line number in roaring.hh shows the error) we might be able to better guess what the problem is.

**Comment by lemire** [comment]
It looks like a genuine problem that we should investigate.

**Comment by e-** [comment]
Thank you for the replies. Changing the order of the includes (first roaring.hh and then windows.h) definitely makes it work. 

Including windows.h first gives me 110 errors and most of them are syntax errors. For example, the __restrict__ keyword in roaring.h does not compile. Maybe windows.h overrides it with its own definition.
All functions that accept an argument named "small", such as `intersect_skewed_uint16(small, size_s, large, size_l, buffer)`, also raise errors perhaps because Windows.h defines "small" as a type name.

Here is the complete list of the errors:

| Severity       | Code  | Description                                            | File       | Line | 
|----------------|-------|--------------------------------------------------------|------------|------| 
| Error          | C2589 | '(': illegal token on right side of '::'               | roaring.hh | 942  | 
| Error (active) | E0040 | expected an identifier                                 | roaring.hh | 781  | 
| Error (active) | E0040 | expected an identifier                                 | roaring.hh | 796  | 
| Error (active) | E0040 | expected an identifier                                 | roaring.hh | 942  | 
| Error (active) | E0040 | expected an identifier                                 | roaring.hh | 950  | 
| Error (active) | E0040 | expected an identifier                                 | roaring.hh | 1063 | 
| Error (active) | E0040 | expected an identifier                                 | roaring.hh | 1067 | 
| Error (active) | E0040 | expected an identifier                                 | roaring.hh | 1068 | 
| Error (active) | E0040 | expected an identifier                                 | roaring.hh | 1072 | 
| Error          | C2589 | '(': illegal token on right side of '::'               | roaring.hh | 781  | 
| Error          | C2062 | type 'unknown-type' unexpected                         | roaring.hh | 781  | 
| Error          | C2059 | syntax error: ')'                                      | roaring.hh | 781  | 
| Error          | C2589 | '(': illegal token on right side of '::'               | roaring.hh | 796  | 
| Error          | C2062 | type 'unknown-type' unexpected                         | roaring.hh | 796  | 
| Error          | C2059 | syntax error: ')'                                      | roaring.hh | 796  | 
| Error          | C2062 | type 'unknown-type' unexpected                         | roaring.hh | 942  | 
| Error          | C2059 | syntax error: ')'                                      | roaring.hh | 942  | 
| Error          | C2143 | syntax error: missing ';' before '{'                   | roaring.hh | 945  | 
| Error          | C2065 | 'map_entry': undeclared identifier                     | roaring.hh | 948  | 
| Error          | C2228 | left of '.second' must have class/struct/union         | roaring.hh | 948  | 
| Error          | C2228 | left of '.cardinality' must have class/struct/union    | roaring.hh | 948  | 
| Error          | C2589 | '(': illegal token on right side of '::'               | roaring.hh | 950  | 
| Error          | C2062 | type 'unknown-type' unexpected                         | roaring.hh | 950  | 
| Error          | C2059 | syntax error: ')'                                      | roaring.hh | 950  | 
| Error          | C2059 | syntax error: ')'                                      | roaring.hh | 952  | 
| Error          | C2059 | syntax error: ':'                                      | roaring.hh | 953  | 
| Error          | C2589 | '(': illegal token on right side of '::'               | roaring.hh | 1063 | 
| Error          | C2062 | type 'unknown-type' unexpected                         | roaring.hh | 1063 | 
| Error          | C2059 | syntax error: ')'                                      | roaring.hh | 1063 | 
| Error          | C2589 | '(': illegal token on right side of '::'               | roaring.hh | 1067 | 
| Error          | C2144 | syntax error: 'unknown-type' should be preceded by ')' | roaring.hh | 1067 | 
| Error          | C2660 | 'Roaring::flip': function does not take 0 arguments    | roaring.hh | 1067 | 
| Error          | C2144 | syntax error: 'unknown-type' should be preceded by ';' | roaring.hh | 1067 | 
| Error          | C2059 | syntax error: ')'                                      | roaring.hh | 1067 | 
| Error          | C2589 | '(': illegal token on right side of '::'               | roaring.hh | 1068 | 
| Error          | C2059 | syntax error: ')'                                      | roaring.hh | 1068 | 
| Error          | C2589 | '(': illegal token on right side of '::'               | roaring.hh | 1072 | 
| Error          | C2144 | syntax error: 'unknown-type' should be preceded by ')' | roaring.hh | 1072 | 
| Error          | C2660 | 'Roaring::flip': function does not take 0 arguments    | roaring.hh | 1072 | 
| Error          | C2144 | syntax error: 'unknown-type' should be preceded by ';' | roaring.hh | 1072 | 
| Error          | C2059 | syntax error: ')'                                      | roaring.hh | 1072 | 
| Error          | C2059 | syntax error: ')'                                      | roaring.hh | 1073 | 
| Error          | C2589 | '(': illegal token on right side of '::'               | roaring.hh | 781  | 
| Error          | C2062 | type 'unknown-type' unexpected                         | roaring.hh | 781  | 
| Error          | C2059 | syntax error: ')'                                      | roaring.hh | 781  | 
| Error          | C2589 | '(': illegal token on right side of '::'               | roaring.hh | 796  | 
| Error          | C2062 | type 'unknown-type' unexpected                         | roaring.hh | 796  | 
| Error          | C2059 | syntax error: ')'                                      | roaring.hh | 796  | 
| Error          | C2589 | '(': illegal token on right side of '::'               | roaring.hh | 942  | 
| Error          | C2062 | type 'unknown-type' unexpected                         | roaring.hh | 942  | 
| Error          | C2059 | syntax error: ')'                                      | roaring.hh | 942  | 
| Error          | C2143 | syntax error: missing ';' before '{'                   | roaring.hh | 945  | 
| Error          | C2065 | 'map_entry': undeclared identifier                     | roaring.hh | 948  | 
| Error          | C2228 | left of '.second' must have class/struct/union         | roaring.hh | 948  | 
| Error          | C2228 | left of '.cardinality' must have class/struct/union    | roaring.hh | 948  | 
| Error          | C2589 | '(': illegal token on right side of '::'               | roaring.hh | 950  | 
| Error          | C2062 | type 'unknown-type' unexpected                         | roaring.hh | 950  | 
| Error          | C2059 | syntax error: ')'                                      | roaring.hh | 950  | 
| Error          | C2059 | syntax error: ')'                                      | roaring.hh | 952  | 
| Error          | C2059 | syntax error: ':'                                      | roaring.hh | 953  | 
| Error          | C2589 | '(': illegal token on right side of '::'               | roaring.hh | 1063 | 
| Error          | C2062 | type 'unknown-type' unexpected                         | roaring.hh | 1063 | 
| Error          | C2059 | syntax error: ')'                                      | roaring.hh | 1063 | 
| Error          | C2589 | '(': illegal token on right side of '::'               | roaring.hh | 1067 | 
| Error          | C2144 | syntax error: 'unknown-type' should be preceded by ')' | roaring.hh | 1067 | 
| Error          | C2660 | 'Roaring::flip': function does not take 0 arguments    | roaring.hh | 1067 | 
| Error          | C2144 | syntax error: 'unknown-type' should be preceded by ';' | roaring.hh | 1067 | 
| Error          | C2059 | syntax error: ')'                                      | roaring.hh | 1067 | 
| Error          | C2589 | '(': illegal token on right side of '::'               | roaring.hh | 1068 | 
| Error          | C2059 | syntax error: ')'                                      | roaring.hh | 1068 | 
| Error          | C2589 | '(': illegal token on right side of '::'               | roaring.hh | 1072 | 
| Error          | C2144 | syntax error: 'unknown-type' should be preceded by ')' | roaring.hh | 1072 | 
| Error          | C2660 | 'Roaring::flip': function does not take 0 arguments    | roaring.hh | 1072 | 
| Error          | C2144 | syntax error: 'unknown-type' should be preceded by ';' | roaring.hh | 1072 | 
| Error          | C2059 | syntax error: ')'                                      | roaring.hh | 1072 | 
| Error          | C2059 | syntax error: ')'                                      | roaring.hh | 1073 | 
| Error          | C2144 | syntax error: 'char' should be preceded by ')'         | roaring.h  | 383  | 
| Error          | C2144 | syntax error: 'char' should be preceded by ';'         | roaring.h  | 383  | 
| Error          | C2059 | syntax error: ','                                      | roaring.h  | 383  | 
| Error          | C2059 | syntax error: ')'                                      | roaring.h  | 385  | 
| Error          | C2144 | syntax error: 'char' should be preceded by ')'         | roaring.h  | 389  | 
| Error          | C2144 | syntax error: 'char' should be preceded by ';'         | roaring.h  | 389  | 
| Error          | C2059 | syntax error: ','                                      | roaring.h  | 389  | 
| Error          | C2059 | syntax error: ')'                                      | roaring.h  | 392  | 
| Error          | C2144 | syntax error: 'char' should be preceded by ')'         | roaring.h  | 396  | 
| Error          | C2144 | syntax error: 'char' should be preceded by ';'         | roaring.h  | 396  | 
| Error          | C2059 | syntax error: ','                                      | roaring.h  | 396  | 
| Error          | C2059 | syntax error: ')'                                      | roaring.h  | 397  | 
| Error          | C2144 | syntax error: 'char' should be preceded by ')'         | roaring.h  | 383  | 
| Error          | C2144 | syntax error: 'char' should be preceded by ';'         | roaring.h  | 383  | 
| Error          | C2059 | syntax error: ','                                      | roaring.h  | 383  | 
| Error          | C2059 | syntax error: ')'                                      | roaring.h  | 385  | 
| Error          | C2144 | syntax error: 'char' should be preceded by ')'         | roaring.h  | 389  | 
| Error          | C2144 | syntax error: 'char' should be preceded by ';'         | roaring.h  | 389  | 
| Error          | C2059 | syntax error: ','                                      | roaring.h  | 389  | 
| Error          | C2059 | syntax error: ')'                                      | roaring.h  | 392  | 
| Error          | C2144 | syntax error: 'char' should be preceded by ')'         | roaring.h  | 396  | 
| Error          | C2144 | syntax error: 'char' should be preceded by ';'         | roaring.h  | 396  | 
| Error          | C2059 | syntax error: ','                                      | roaring.h  | 396  | 
| Error          | C2059 | syntax error: ')'                                      | roaring.h  | 397  |

**Comment by lemire** [comment]
Could you have a look at the latest commit?

https://github.com/RoaringBitmap/CRoaring/commit/fa9e9a1cce4b65284b77fa18a06d8d7ba62557ad

I was able to compile a non-trivial program that uses CRoaring after adding the offending Windows.h header without any error after making these tiny changes.

If you get more errors, make sure to describe them so that they are easier to fix.

I'll wait for your feedback before closing this issue.

**Comment by e-** [comment]
It works! Thank you very much!

**Comment by madscientist** [comment]
You might want to add a quick comment to the first one explaining why these extra parentheses exist, so someone in the future doesn't remove them as superfluous.  Just a thought.

I get why MS is so conservative about these things but it's a real bummer that they haven't found the fortitude to bite the bullet and get rid of all this brokenness with one "fix it all" Visual Studio release, where everyone just knows they have to rework their code to be more standards-compliant for that release and beyond.

**Comment by lemire** [comment]
@madscientist  I did add the suggested comments.

I have just issued a release.

**Comment by e-** [comment]
I'll close this issue. Thanks.
