### ISSUE TITLE
Iterate over values greater than or equal to an integer x (in C++ ideally)

### ISSUE THREAD

**Issue by GuillaumeHolley** [RoaringBitmap/CRoaring#121]
Hello everyone!

First of all, thank you very much for developing Roaring, it is just super useful and easy to use :)

I was wondering if there is a simple way to iterate over all values of a Roaring bitmap that are greater than or equal to an integer _x_? Something like `Roaring::const_iterator it = t.contains(x);` where `contains()` returns an iterator instead of a boolean. Or if it is not possible, maybe a way to start from an integer not too far from _x_?
Maybe the functionality is already there and I didn't see it, in which case I apologize in advance. Seems like it is related to issue #60 but I don't know if there was any follow up on this (knowing that the issue is still open).

Thank you in advance and have a nice day!

Best,
Guillaume

**Comment by lemire** [comment]
Resolved with the latest commit 

https://github.com/RoaringBitmap/CRoaring/commit/b0154842da0edc420ff97f9ba4ba50f4640a5d02

Please test.
