### ISSUE TITLE
[C++] Inconsistent inline documentation

### ISSUE THREAD

**Issue by WojciechMula** [RoaringBitmap/CRoaring#123]
https://github.com/RoaringBitmap/CRoaring/blob/5bd4e7c4c01a9161dd8b0511d1ce7347c6b620c2/cpp/roaring.hh#L296

The description of `roaring_iterator` type is wrong and not as detailed as in C header.

**Comment by lemire** [comment]
Can you propose something that would be better?

**Comment by WojciechMula** [comment]
Sure; I will prepare MR, but not today.

**Comment by WojciechMula** [comment]
Sorry that it took so long, the MR #124
