### ISSUE TITLE
[Question] Why Roaring64Map::end() does not return static object?

### ISSUE THREAD

**Issue by 0ctopus13prime** [RoaringBitmap/CRoaring#125]
Hi! 
Just out of pure curiosity or maybe i'm not c++ expert 
but, contrast to Roaring::end() is there any reason for Roaring64Map::end not return static object?

I'm worry `end()` method be called every time in the loop.
Ex)
```
while(it != roaring64::end()) {
  // Doing something ...
}
```

Does compiler will make enough optimization about this?
If i'm wrong plz fix me!

Thanks.

**Comment by ksajme** [comment]
Please see:
https://github.com/RoaringBitmap/CRoaring/pull/86
