### ISSUE TITLE
Add to Microsoft's VC++ Packaging Tool

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/CRoaring#135]
Microsoft launched a package manager that should be supported by this library...

https://github.com/Microsoft/vcpkg

**Comment by lemire** [comment]
cc @myd7349

**Comment by myd7349** [comment]
Hi! @lemire I have created a PR for this in `vcpkg`. And it is almost done.

Before merging, I'd like to confirm something with you.

1. Is it fine to name the package as `roaring`?

2. The installed header files will have a structure like this:

![Header](https://user-images.githubusercontent.com/5435649/54347220-8950a500-4681-11e9-99fa-8ac1b4620598.png)

is this as expected?

Thanks!

**Comment by lemire** [comment]
@myd7349 That would be fantastic.


1. `roaring` is probably fine. The name of the library is `CRoaring` but I don't think it matters too much what the exact name is.

2. At a glance, the headers look fine to me, don't they look fine to you?

**Comment by myd7349** [comment]
@lemire Thanks for your reply!

For 2, I was wondering whether `roaring.hh` and `roaring64map.hh` shoud be put outside of `roaring` since I see `#include <roaring/roaring.h>` in them.  Now I have no problem.

**Comment by lemire** [comment]
So the header files should be in a roaring subdirectory... like simdjson header files are in a simdjson subdirectory... is that correct?

Do we have the possibility of doing post-installation tests to ensure that everything is working?

**Comment by myd7349** [comment]
@lemire Sorry. I didn't make it clear.

All of these headers are under a `roaring` subdirectory. And the structure is:

```
E:\VCPKG\INSTALLED\X86-WINDOWS-STATIC\INCLUDE
│
└─roaring
    │  array_util.h
    │  bitset_util.h
    │  portability.h
    │  roaring.h
    │  roaring.hh
    │  roaring64map.hh
    │  roaring_array.h
    │  roaring_types.h
    │  roaring_version.h
    │  utilasm.h
    │
    ├─containers
    │      array.h
    │      bitset.h
    │      containers.h
    │      convert.h
    │      mixed_andnot.h
    │      mixed_equal.h
    │      mixed_intersection.h
    │      mixed_negation.h
    │      mixed_subset.h
    │      mixed_union.h
    │      mixed_xor.h
    │      perfparameters.h
    │      run.h
    │
    └─misc
            configreport.h
```

I am just not sure whether it should be:

```
E:\VCPKG\INSTALLED\X86-WINDOWS-STATIC\INCLUDE
│  roaring.hh
│  roaring64map.hh
│
└─roaring
    │  array_util.h
    │  bitset_util.h
    │  portability.h
    │  roaring.h
    │  roaring_array.h
    │  roaring_types.h
    │  roaring_version.h
    │  utilasm.h
    │
    ├─containers
    │      array.h
    │      bitset.h
    │      containers.h
    │      convert.h
    │      mixed_andnot.h
    │      mixed_equal.h
    │      mixed_intersection.h
    │      mixed_negation.h
    │      mixed_subset.h
    │      mixed_union.h
    │      mixed_xor.h
    │      perfparameters.h
    │      run.h
    │
    └─misc
            configreport.h
```

**Comment by lemire** [comment]
The C++ headers used to be located in roaring/cpp following installation. There was a request to move them directly in the roaring subdirectory, as per...
https://github.com/RoaringBitmap/CRoaring/issues/119

So that's where they are supposed to go after installation. 

If this causes difficulties, I'd like to know about it. But yeah, the layout you describe is the one intended.

**Comment by myd7349** [comment]
@lemire Got it. Thanks again!

**Comment by lemire** [comment]
@myd7349  How the heck do you people upload screenshots to github like that?

**Comment by myd7349** [comment]
@lemire  In fact, I don't know how others do this. For me,  there is nothing special. What I did is(I use Firefox on Win10):

- Make a screenshot by pressing `PrintScreen` key
- Paste it into GitHub's edit box from the clipboard by pressing `Ctrl+V`
- GitHub will upload the image for you

 You may also edit the image just before pasting.

 By the way, it seems that GitHub also supports `drag & drop`.

**Comment by myd7349** [comment]
@lemire I also have a question. I see people use `cc`  here and there on GitHub,  what does it mean?

**Comment by myd7349** [comment]
Hi! @lemire The PR has been merged.

**Comment by lemire** [comment]
Fantastic. I have verified that it works. Closing the issue.
