### ISSUE TITLE
Add "roaring_bitmap_remove_many" function

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/CRoaring#137]
We would like to have a ``roaring_bitmap_remove_many`` function which allows you to remove from a bitmap all of the elements from an array. This can be done currently with repeated calls to ``roaring_bitmap_remove``. But it would be more convenient and efficient to have a dedicated function.

**Comment by GuillaumeHolley** [comment]
Now that we have functions to add and query ranges of values, it would also make sense to have a `roaring_bitmap_remove_range` function I think.

**Comment by lemire** [comment]
Agreed.

**Comment by andreigudkov** [comment]
OK, I will implement it.

**Comment by lemire** [comment]
+1

**Comment by andreigudkov** [comment]
Both functions (`remove_many`, `remove_range`) are already implemented. This issue can be closed, I think.

**Comment by lemire** [comment]
Closing.
