### ISSUE TITLE
Access violation in array_container_benchmark

### ISSUE THREAD

**Issue by berendeanicolae** [RoaringBitmap/CRoaring#139]
When running the array_container_benchmark both on Windows and Linux, the program crashes at line #169 in `array.c`. 

https://github.com/RoaringBitmap/CRoaring/blob/e03a925c82688c95b251c010fa65b161c9f5f385/src/containers/array.c#L169

In my tests, the two arrays have cardinality 21846 and 13108.
`input 1 cardinality = 21846, input 2 cardinality = 13108`

I believe the issue is caused by having the upper limit be a constant `2 * DEFAULT_MAX_SIZE` instead of `max_cardinality`.

I ran the benchmarks on a i7 4600u if it has any relevance.

**Comment by lemire** [comment]
Indeed, I fixed the issue.
