### ISSUE TITLE
Best way to query for presence/absence of a range of values?

### ISSUE THREAD

**Issue by GuillaumeHolley** [RoaringBitmap/CRoaring#141]
Hello,

I need to query very quickly a lot of Roaring bitmaps for the presence of a lot of range of values. More specifically, for a bitmap `R` and a range of values `[v_start, v_end]`, I need to know if ALL values from `v_start` to `v_end` are in `R` (which values are missing or how many are missing is not relevant).

The naive way to do this would be obviously to query `R` for each value from `v_start` to `v_end`.
Then, I thought that what could be more efficient would be to query for `v_start`  and `v_end`: if both are present, I compute`rank(v_end) - rank(v_start - 1) == length([v_start, v_end])`.
Another possibility would be to create a new Roaring bitmap `R_range` with all the values of my range, then use `R_range.isSubset(R)`.

Do you know which way would be the best or if there is another better way to achieve this?

Thank you very much and have a nice day!

Guillaume

**Comment by Ezibenroc** [comment]
You cannot compute `rank(v_start -1)` if `v_start` is 0. Instead, you should check this:
`rank(v_end) - rank(v_start) + 1 == v_end - v_start + 1`

Regarding the efficiency, the naive method is of course terrible. I did a quick comparison of the two other methods, using [pyroaring](https://github.com/Ezibenroc/PyRoaringBitMap).

```python
from pyroaring import BitMap

def all_present_subset(bitmap, start, end):
    return BitMap(range(start, end+1)) <= bitmap

def all_present_rank(bitmap, start, end):
    if start not in bitmap or end not in bitmap:
        return False
    r_start = bitmap.rank(start)
    r_end = bitmap.rank(end)
    return r_end - r_start + 1 == end-start+1

N=1000000000
bitmap = BitMap(range(1, N))
%time all_present_subset(bitmap, 1, N)
%time all_present_rank(bitmap, 1, N)
```

Result:
```
CPU times: user 38.1 ms, sys: 997 µs, total: 39.1 ms
Wall time: 38.8 ms
CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 4.77 µs
```

So it seems that, for large N, the rank method is several orders of magnitude faster. I expect the overhead caused by Python to be negligible for such N, but feel free to reproduce this test in C.

One possible optimization for the rank method could be to avoid the existence query, e.g. with a function that returns the rank of the element if it exists and 0 otherwise.

**Comment by GuillaumeHolley** [comment]
First of all, thank you for your help!

@fsaintjacques : No, bitmap are not static when I would need to call this range querying function. On my smaller dataset here, I have 5 million bitmaps and about 600 ranges to test per bitmap (probably multiple times per bitmap). A big dataset would be around 250 million bitmaps and up to 100,000 ranges per bitmap (and the ranges are not the same for each bitmap).
I agree I would be better of having my own method, especially that the ranges I have to test are sorted and do not overlap, i.e, for two ranges [v1_start, v1_end] and [v2_start, v2_end], v2_start > v1_end. I just thought their was maybe something already in place.

@Ezibenroc : thanks for the benchmarking. I will probably go with the ranking method first and see how much of a bottleneck it is. I will try to benchmark as well how much the existence query takes compared to the ranking computation, just to see if the optimization is worth it.

**Comment by lemire** [comment]
The Java version has a dedicated function for this implemented by @richardstartin ...
https://github.com/RoaringBitmap/RoaringBitmap/pull/237/files

It would not be hard to port this over to C. It is probably about 200 lines of code.

**Comment by richardstartin** [comment]
I didn’t think of the rank approach, it’s probably worth benchmarking the contains method against two calls to rank (in Java) before porting it. I imagine contains will do slightly better when the range is towards the end of a large bitmap.

**Comment by richardstartin** [comment]
I wrote a quick [benchmark](https://github.com/RoaringBitmap/RoaringBitmap/pull/250), designed to be slightly unfair to rank by making sure the start and inclusive end of the range are always in the bitmap. It's worth porting this code, rather than using rank:

```
Benchmark                      (keys)  (match)  (scenario)  Mode  Cnt     Score     Error  Units
ContainsRange.contains              8     true       START  avgt    5     0.061 ±   0.006  us/op
ContainsRange.contains              8     true         END  avgt    5     0.028 ±   0.001  us/op
ContainsRange.contains              8    false       START  avgt    5     0.320 ±   0.005  us/op
ContainsRange.contains              8    false         END  avgt    5     0.046 ±   0.001  us/op
ContainsRange.contains             32     true       START  avgt    5     0.150 ±   0.002  us/op
ContainsRange.contains             32     true         END  avgt    5     0.532 ±   0.038  us/op
ContainsRange.contains             32    false       START  avgt    5     0.031 ±   0.001  us/op
ContainsRange.contains             32    false         END  avgt    5     0.050 ±   0.001  us/op
ContainsRange.contains           8192     true       START  avgt    5     1.382 ±   0.020  us/op
ContainsRange.contains           8192     true         END  avgt    5     1.314 ±   0.018  us/op
ContainsRange.contains           8192    false       START  avgt    5     0.044 ±   0.001  us/op
ContainsRange.contains           8192    false         END  avgt    5     0.022 ±   0.001  us/op
ContainsRange.containsViaRank       8     true       START  avgt    5     0.036 ±   0.001  us/op
ContainsRange.containsViaRank       8     true         END  avgt    5     2.991 ±   0.242  us/op
ContainsRange.containsViaRank       8    false       START  avgt    5     0.271 ±   0.076  us/op
ContainsRange.containsViaRank       8    false         END  avgt    5     3.425 ±   0.145  us/op
ContainsRange.containsViaRank      32     true       START  avgt    5     0.197 ±   0.003  us/op
ContainsRange.containsViaRank      32     true         END  avgt    5     6.825 ±   0.104  us/op
ContainsRange.containsViaRank      32    false       START  avgt    5     0.032 ±   0.001  us/op
ContainsRange.containsViaRank      32    false         END  avgt    5     0.055 ±   0.001  us/op
ContainsRange.containsViaRank    8192     true       START  avgt    5     1.224 ±   0.029  us/op
ContainsRange.containsViaRank    8192     true         END  avgt    5  3077.598 ± 133.395  us/op
ContainsRange.containsViaRank    8192    false       START  avgt    5     0.040 ±   0.001  us/op
ContainsRange.containsViaRank    8192    false         END  avgt    5     0.018 ±   0.001  us/op

```

**Comment by lemire** [comment]
There is now a PR produced by @GuillaumeHolley  to solve this. We need testing before we can release it.
