### ISSUE TITLE
syntax error in amalgamated source by VS 2017 C++ compiler

### ISSUE THREAD

**Issue by cjmay** [RoaringBitmap/CRoaring#146]
Hi,

I get a syntax error when building the amalgamated source using the MS Visual Studio 2017 C++ compiler.  It appears designated initializer lists, which are used a few times in the source, [are not valid C++11](https://stackoverflow.com/questions/18731707/why-does-c11-not-support-designated-initializer-lists-as-c99)?  Perhaps gcc/clang C++ support them anyway?

The compiler also throws errors about the parentheses around the types of the objects created by designated initializer lists.

After removing the parentheses and designators, the amalgamated C++ file compiles cleanly.  For illustration, the first change to the source is from:

```c++
(rle16_t){.value = (uint16_t)start,
          .length = (uint16_t)(end - start - 1)};
```

to:

```c++
rle16_t{(uint16_t)start,
        (uint16_t)(end - start - 1)};
```

I am building CRoaring in the process of building the [PyRoaring](https://github.com/Ezibenroc/PyRoaringBitMap) extension module.  I saw #115, but I am not sure how the instructions in the README pertain to this syntax, or how I would apply them to the PyRoaring build.  If there is a way to adjust the build without modifying the CRoaring code, please let me know!  I would be very appreciative.

Thank you,
Chandler

**Comment by lemire** [comment]
CRoaring is written in C. It definitively does build under Visual Studio, we test this as part of our CI:

https://ci.appveyor.com/project/lemire/croaring

In fact, the library is used by Microsoft internally.

When I talk the amalgamated files and I create a silly Visual Studio project with them, it works well, try it...

https://github.com/lemire/croaringfun

(Just clone it, open croaringfun.sln in Visual Studio 2017, then select "build". It will build a simple console app. It should run. I think it assumes x64 so on ARM you may need different project settings.)

However, I see that you are building the c source files as C++ (your file is roaring.cpp not roaring.c). That's likely what is causing a problem. I have opened a new issue...

https://github.com/Ezibenroc/PyRoaringBitMap/issues/31

I am closing this issue as I think  I have provided an answer to:

>  If there is a way to adjust the build without modifying the CRoaring code, please let me know! I would be very appreciative.

The answer is, quite simply, replace the roaring.cpp by a roaring.c, and make sure that Visual Studio treats roaring.c as a C source file, not as a C++ source file. 

Reopen if it does not work, but make sure you have tried the croaringfun project above before concluding that there is a problem.

**Comment by cjmay** [comment]
Thanks for the thorough explanation and help!  I am sure it works for C (I take you at your word, and had seen the appveyor configuration previously), but I guess my confusion was expecting it to work the same way for C++.  Compiling the amalgamated source with C seems to fix the issue.

**Comment by lemire** [comment]
@cjmay 

It is not trivial. That's why I provide proof.

**Comment by madscientist** [comment]
Just to be clear, although C++ has its roots in C it's not the case that C++ is strict superset of C (at least not for all C standard versions).  Compiling a standard-conforming C file with a C++ compiler may work depending on what features the C code uses, but it is definitely not guaranteed to work and should be avoided.  All the major C++ compilers also come with C compilers, so it's no trouble, typically, to use the correct one.  Cheers!
