### ISSUE TITLE
bitset_range_cardinality() incorrect result

### ISSUE THREAD

**Issue by andreigudkov** [RoaringBitmap/CRoaring#149]
When `end` argument is a multiple of 64, this function produces incorrect result. Other `bitset_util.h` functions may also contain the same error.

This [line](https://github.com/RoaringBitmap/CRoaring/blob/master/include/roaring/bitset_util.h#L46) is the source of the problem. It generates zero mask instead of "all ones":

    answer += hamming(bitmap[endword] & ((~UINT64_C(0)) >> (64 - (end % 64))));

Following test case demonstrates the bug:
```
void test_bitset_range_cardinality() {
  uint64_t words[] = {~UINT64_C(0), ~UINT64_C(0)};
  assert(bitset_range_cardinality(words, 0, 127) == 127); // ok
  assert(bitset_range_cardinality(words, 0, 128) == 128); // error
  /*
  for (int i = 0; i < 256; i++) {
    for (int j = i; j < 256; j++) {
      assert(bitset_range_cardinality(words, i, j) == (j-i));
    }
  }
  */
}
```

**Comment by lemire** [comment]
This dead and incorrect code. This is not the code we actually use.

**Comment by lemire** [comment]
The function was removed. Thanks for reporting the problem.
