### ISSUE TITLE
deserialization from a char pointer with same content

### ISSUE THREAD

**Issue by ChenZhongPu** [RoaringBitmap/CRoaring#155]
Here is the sample code from [CRoaring](https://github.com/RoaringBitmap/CRoaring):

    uint32_t expectedsize = r1.getSizeInBytes();
    char *serializedbytes = new char [expectedsize];
    r1.write(serializedbytes);
    Roaring t = Roaring::read(serializedbytes);
    assert(r1 == t);
    delete[] serializedbytes;

Suppose `r1` is create from

    const uint32_t values[] = {5, 2, 3, 4, 1};
    Roaring r1(5, values);

Then, `strlen(serializedbytes) == 2`.

The problem is: if we copy `serializedbytes` to a new char pointer, the deserialization is not expected:

    char *copy = new char[3]; // or: char *copy = new char[expectedsize];
    strcpy(copy, serializedbytes);
    Roaring t2 = Roaring::read(copy);

Now `t2` is empty! 

So, since contents of `serializedbytes` and `copy` are the same, why `copy` cannot be read by a roaring?

**Comment by lemire** [comment]
@ChenZhongPu 

Please do not use ``strlen`` or ``strcpy`` for this purpose. There are string functions. Roaring is serialized to binary... not string.

The correct approach is as follows...

 ```c
  uint32_t values[] = {5, 2, 3, 4, 1};
  Roaring r1(sizeof(values)/sizeof(uint32_t), values);
  uint32_t serializesize = r1.getSizeInBytes();
  char *serializedbytes = new char [serializesize];
  r1.write(serializedbytes);
  Roaring t = Roaring::read(serializedbytes);
  assert_true(r1 == t);
  char *copy = new char[serializesize];
  memcpy(copy, serializedbytes, serializesize);
  Roaring t2 = Roaring::read(copy);
  assert_true(t2== t);
  delete[] serializedbytes;
  delete[] copy;
```

If you need an actual ASCII string, you can use base64 encoding.

Reopen if this does not answer your question.
