### ISSUE TITLE
Calling roaring_bitmap_add_range with copy_on_write gives a segmentaiton fault

### ISSUE THREAD

**Issue by Ezibenroc** [RoaringBitmap/CRoaring#156]
The following example shows the error (file `test.c`):
```c
#include "roaring.c"

int main() {
    roaring_bitmap_t *r1 = roaring_bitmap_from_range(0, 1, 1);
    r1->copy_on_write = true;
    roaring_bitmap_t *r2 = roaring_bitmap_copy(r1);
    roaring_bitmap_add_range(r1, 0, 1);
    return 0;
}
```
Compile and run with:
```bash
./amalgamation.sh
cc -march=native -O0 -std=c11 -g -o test test.c
./test
```
Removing any line from the C file prevents the error from happening. The error still happens with other compilation flags and without amalgamation.

**Comment by andreigudkov** [comment]
I'll look into this.

**Comment by lemire** [comment]
Hopefully that PR by @andreigudkov  fixed this. I'll close but please verify.
