### ISSUE TITLE
Implement "equals"

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/CRoaring#16]
We should be able to quickly check equality between bitmaps.

**Comment by fsaintjacques** [comment]
See branch feature/equals-impl for a start. It also contains a refactor of test.

**Comment by fsaintjacques** [comment]
The goal is that once we know `*_container_equal` functions are valid, tests should be much cleaner an easy to write.

**Comment by lemire** [comment]
@fsaintjacques 

I reviewed the code in your branch and it looks fine to me. I guess you want to finish up the implementation before merging into ``master`` right?

Yes. The unit testing code is not pretty. I wrote "something" since, as far as tests goes, something is a lot better than nothing... but I have no qualm about it being refactored... as long as the new tests are not weaker, obviously.

**Comment by lemire** [comment]
Implemented.

Inviting @fsaintjacques  to improve our tests.
