### ISSUE TITLE
Compiler warning: roaring_array.c:ra_portable_deserialize() has bad printf format

### ISSUE THREAD

**Issue by madscientist** [RoaringBitmap/CRoaring#162]
In roaring_array.c:ra_portable_deserialize() we have:
```
    if (size > (1<<16)) {
       fprintf(stderr, "You cannot have so many containers, the data must be corrupted: %u\n",
               size);
       return false; // logically impossible                                    
    }
```
This gives warnings (GNU/Linux, GCC 8.1.0) because `size` is of type `size_t` which is (on GNU/Linux) `unsigned long`.  Unfortunately on Windows `size_t` is `unsigned long long`, and anyway only recent Windows compilers support C99 (!!) where `long long` was added to printf formatting.  So there's no simple, portable way to print a `size_t` due to Windows silliness *sigh*.

I changed the code to this:
```
    if (size > (1<<16)) {
       fprintf(stderr, "You cannot have so many containers, the data must be corrupted: %lu\n",
               (unsigned long)size);
       return false; // logically impossible                                    
    }
```

**Comment by lemire** [comment]
> This gives warnings

I don't think we aim to be free of compil


> because `size` is of type `size_t`

The variable `size` is defined as `int32_t size`.

> So there's no simple, portable way to print a size_t due to Windows

This should do the trick `print("%zu", x)`. 

> I changed the code to this

I don't think that's the formally correct way to print an int32_t. 

I think I used the formally correct way in this commit:

https://github.com/RoaringBitmap/CRoaring/commit/77918be33ad1d5c988618479ed387c96e74ca883

Closing.

**Comment by madscientist** [comment]
> I don't think we aim to be free of compil

I use the amalgamation source and when I compile it I use all the same compiler flags for it that I use for the rest of my code, so it has the same debugging settings etc... and I always have full warnings and `-Werror` enabled in my code so if there are warnings in Roaring my build fails.  If I created Roaring as a separate library that I compiled externally with its own set of flags and linked, it would be different... but that makes it too hard for me to use (I have to build it multiple ways with different configurations).

> This should do the trick print("%zu", x).

As I mentioned this relies on compilers supporting the C99 standard.  Only the last few versions of Visual Studio support C99; prior to that it only supported C90.  If you want to restrict to newer versions of Visual Studio it will work.  However this doesn't matter because:

> The variable size is defined as int32_t size.

Oops, you're right, I got confused somehow with the `maxbytes` variable which is of `size_t`.  Sorry about that ... :(

Converting to use `%d` instead of `%u` would work as well (on all your supported platforms) but your change is more standards-conformant.

**Comment by lemire** [comment]
> Only the last few versions of Visual Studio support C99

I don't think that even the very latest Visual Studio is C99.

"The Visual C++ C compiler is generally compatible with the ISO C99 standard, but not strictly compliant. In most cases, portable C code will compile and run as expected. "
https://docs.microsoft.com/en-us/cpp/build/walkthrough-compile-a-c-program-on-the-command-line

We had a revert back several C99 features to get the code to compile under Visual Studio 2017. It would be nice if it were C99 compliant.

> If you want to restrict to newer versions of Visual Studio it will work.

As far as I know, `%zu` works with at least Visual Studio 2015 and better.
