### ISSUE TITLE
Allow `march=` target to be specified during build

### ISSUE THREAD

**Issue by kanak** [RoaringBitmap/CRoaring#176]
Our build servers have slightly different CPUs from our production machines, and our production machines themselves are varied. We've started disabling `march=native` after we had a `SIGILL` crash when running a binary built on a machine with a newer CPU. 

It would be better if we could instead specify the value of `march`. In our case, we would pass `march=westmere` which is the oldest CPU that we use.

I'm happy to submit a patch to implement this feature, but I'm not sure if you would like this to replace the existing functionality, or if you would like the two to work together.

Thanks!

**Comment by lemire** [comment]
Sounds good. PR invited.

**Comment by lemire** [comment]
Fixed.
