### ISSUE TITLE
Export roaring_bitmap_overwrite

### ISSUE THREAD

**Issue by joebone** [RoaringBitmap/CRoaring#180]
**roaring_bitmap_overwrite** isn't exported as an entrypoint in the external api, which makes object reuse/ pooling more difficult than it has to be in libraries(i.e CRoaring.Net) used in managed languages.

Would it be possible to expose that method in the extern section so that the downstream consumers could reuse their instances, _assuming of course they have ensured there is sufficient memory in the buffers, etc_.?

**Comment by lemire** [comment]
Fixed in HEAD.

**Comment by lemire** [comment]
To be part of a future release.

**Comment by joebone** [comment]
that was some speedy reaction ;) much obliged!

**Comment by lemire** [comment]
@joebone If you could test it out, that'd be great.

**Comment by joebone** [comment]
So, forked, cloned, checked out head, but running into some issues using cmake for the first time. I'll take another crack tomorrow, but honestly looking at the code, I don't see how it could not work ;)

**Comment by lemire** [comment]
We have CI so our tests run continuously and they are fine. Everything works on my machine as well.

**Comment by joebone** [comment]
I got there in the end.. the dll built in clang was double the size the included version of CRoaring.Net is using, but after including the newer one, adding the relevant imports, and extending his c# interface to include the wrapper:

```
[DllImport("roaring")]
public static extern bool roaring_bitmap_overwrite(IntPtr destination, IntPtr source);
// ....
public bool OverwriteFrom(RoaringBitmap source) => NativeMethods.roaring_bitmap_overwrite(_pointer, source._pointer);
```

 just tested in a basic c# console app:
```
 static void Main(string[] args)
        {
            RoaringBitmap rr = new RoaringBitmap();
            rr.Add(2);
            Console.WriteLine(string.Join(",", rr.ToArray()));


            RoaringBitmap rr2 = new RoaringBitmap();
            rr2.Add(1);
            rr2.Add(3);
            Console.WriteLine(string.Join(",", rr2.ToArray()));


            rr2.OverwriteFrom(rr);
            Console.WriteLine(string.Join(",", rr2.ToArray()));

            Console.ReadKey();
        }
```
and all is working as expected =) Thanks very much!
