### ISSUE TITLE
getting bitmap of container?

### ISSUE THREAD

**Issue by amitdesai03** [RoaringBitmap/CRoaring#183]
Is there way to get bitmap for an container? I know underlying containers can be of type array or bitset or run. 

However what i am interested in getting, is just the bitset represented by container values.

For example if continer has value "1","2" and "5" set, than output should be bit set like
"...00010011"

**Comment by lemire** [comment]
I am not quite clear on what you are asking. Do you want to map a Roaring Bitmap to an uncompressed bitset? Is that the question?

**Comment by lemire** [comment]
There is no bitset implementation in C by default. So you'd need to provide the bitset data structure. I do have a decent implementation:
https://github.com/lemire/cbitset

It could be bundled with CRoaring and you could have a way to go back and forth between the two.

Not sure this is what you want.

**Comment by amitdesai03** [comment]
Thanks, Yes I wanted way to access uncompressed bitmap so as can do direct bitwise operations.

Basically i need efficient way to know below:
Given an range, find out all consecutive unset bits. This cannot be done with API supported directly by roaring bitmap. 

Can you please explain how can you bundle cbitset and croaring?

**Comment by lemire** [comment]
> Given an range, find out all consecutive unset bits. This cannot be done with API supported directly by roaring bitmap.

It is true that the current API does not directly support iterations over unset bits. However you can definitively iterate over the set bits within a range, and thus you can hack some way to iterate over the unset bits... with code like this...

```C
roaring_bitmap_t *ra =...
roaring_uint32_iterator_t   i;
roaring_create_iterator(ra, &i);
bool hasvalue =  roaring_move_uint32_iterator_equalorlarger(it, minimum) ;
uint32_t current = minimum;
while(hasvalue) {
  if(i.current_value >= maximum) {
    while(current < i.current_value) {
    // do something with current
    }
    break;// we are done
  }
  while(current < i.current_value) {
    // do something with current
  }
  roaring_advance_uint32_iterator(&i);
  current = i.value + 1;
  hasvalue = i.has_value;
}
```


Converting to a bitset to get the job done looks like a serious overkill.

I am not 100% sure of what you need, but I am not convinced that you can't do it using the current API. Can you elaborate?

Note: The Java and Go versions allow iterations over unset bits. That's not hard to implement.

**Comment by amitdesai03** [comment]
Yes, we can have iterator to iterate over unset bits. However it wont be very efficient for my use case.

I can efficiently find first unset groups of bit, using bitwise operators like '~'  and '>>' on direct uncompressed bitset.

From what i understand, these operators are not supported as of today in roaring.

**Comment by lemire** [comment]
> Can you please explain how can you bundle cbitset and croaring?

There is no magic, but it can be programmed. Someone needs to do the work.

> From what i understand, these operators are not supported as of today in roaring.

They are supported in `cbitset` but it is not magically fast.

**Comment by amitdesai03** [comment]
It would be great if there is support for some of those operators in future
Thanks.

**Comment by lemire** [comment]
Sure. Pull requests invited. Note that a shift is not cheap.
