### ISSUE TITLE
Implement backwards iteration

### ISSUE THREAD

**Issue by Brian-Esch** [RoaringBitmap/CRoaring#189]
We have a use a use case for iterating though a bitmap backwards; we want to to find the closest N neighbors to an entry. The easiest way to do this is to use `roaring_move_uint32_iterator_equalorlarger` and then move around that point with iterators. 

I've got a couple patches which implement this behavior which I could submit as a PR if there is interest! Not sure if this is an issue but it does break ABI compatibility since I removed the `in_run_index` member from the `roaring_uint32_iterator_s`.

**Comment by lemire** [comment]
That would be fantastic.

> it does break ABI compatibility

Personally, I can live with that, but it is good to point it out.

**Comment by Brian-Esch** [comment]
Created a PR: https://github.com/RoaringBitmap/CRoaring/pull/190

**Comment by lemire** [comment]
Closed by @Brian-Esch who has been added as an author.
