### ISSUE TITLE
C++: noexcept moves, cheaper default construction

### ISSUE THREAD

**Issue by kanak** [RoaringBitmap/CRoaring#191]
First off, thank you for Roaring -- we're using it heavily and it's worked great. We were wondering if you'd be open to a couple of improvements to the C++ API, specifically around the behavior of moves and default construction.

### Cheap Default Construction
Currently `Roaring()` does an `ra_init()` and constructs a bitmap with capacity 4 -- which involves memory allocation.  This is a bit confusing to C++ programmers, because most containers (STL, boost, etc) have very simple & fast default constructors that simply set a few fields on the stack, and in particular do not do operations that could fail such as heap allocation. 

It would be great if Roaring class's default constructor avoided heap allocations, possibly by using `ra_init_with_capacity(ptr, 0)`.

### `noexcept` move constructor and move assign

These methods currently can fail because they need to `ra_init` with capacity 1. As such, they cannot be marked as `noexcept`.

This has performance implications; for example, when we make a `std::vector<Roaring>`, it needs to use copy construction during resizes instead of using move.  Details [here](http://blogs.microsoft.co.il/sasha/2014/08/08/make-move-constructors-no-throw/)

This is related to the previous point because if we had a cheap and "cannot fail" default construction, we could use that as the "moved out state".

### Workarounds
We are currently working around these issues by putting the bitmap itself in a `std::unique_ptr<>`. This is a bit suboptimal since we've added an extra layer of indirection.

We're happy to help with the implementation if there is a consensus on the solution.

**Comment by lemire** [comment]
I trust we can close this.
