### ISSUE TITLE
C++ implementation should be namespaced

### ISSUE THREAD

**Issue by jbayardo** [RoaringBitmap/CRoaring#197]
If you use CRoaring as it comes in the library, it generates a name clash with the Point Cloud Library. This is because of the `#include "roaring.h"` line in the head of `roaring.hh`, causing it to bring many functions into the global namespace.

I have "fixed this" by creating

roaring.h
```
#pragma once

namespace roaring {
#include <roaring/roaring.hh>
}
```

And including that directly, but it seems like this should be handled library-level.

**Comment by AE1020** [comment]
I have already [patches to get the entirety of roaring to build as C++](https://github.com/AE1020/CRoaring/commit/8663249b90bff20a24c6eefd476712a11a85c333), which corrects issues like spanning header files with `extern "C" { }`.

Namespaces similarly should not span headers and only roaring-specific content, so they can go at those locations.  So:

     #ifdef __cplusplus
     extern "C" { namespace roaring {
     #endif

I first tried [everything under one namespace](https://github.com/AE1020/CRoaring/commit/80f5db6e550d9924faa8828bd067c3601a30aec4), which works but it would lead people to saying `using namespace roaring;` when they want much less.

Then split this up into [::roaring for the C++ exports, ::roaring::api for the C public API vs. ::roaring::internal for service routines](https://github.com/AE1020/CRoaring/commit/2e2e0da6fde5e364169895d84338304e54fa9c4d).

To the extent anyone knows what namespace best practices are, it tries to follow them by not doing `using` statements in headers unless it has to for C compatibility.

**Comment by lemire** [comment]
@AE1020 Could you issue a PR?

**Comment by lemire** [comment]
This has been fixed.
