### ISSUE TITLE
It seems the statistics of memory consumption are problematic

### ISSUE THREAD

**Issue by helifu** [RoaringBitmap/CRoaring#203]
For typecode of ARRAY_CONTAINER_TYPE_CODE , the memory is allocated here:
https://github.com/RoaringBitmap/CRoaring/blob/9189f451ddd972dc0a3e4f36d6a46d940c5d5803/src/containers/array.c#L121
L126~L133

but the statistics here is strange:
https://github.com/RoaringBitmap/CRoaring/blob/9189f451ddd972dc0a3e4f36d6a46d940c5d5803/include/roaring/containers/array.h#L207

Should not be "container->capacity* sizeof(uint16_t);" ? Or am i missing something?

**Comment by lemire** [comment]
The size of the container is given by `cardinality` so the `array_container_size_in_bytes` must be derived from the cardinality. Of course, we could also have a `array_container_capacity_in_bytes` function.

**Comment by helifu** [comment]
No, i can't agree with you.  
`    uint32_t n_bytes_array_containers;  /* number of allocated bytes in array
                                           containers */`
Why does the bitset container return the allocated size? 
`static inline int32_t bitset_container_size_in_bytes(
    const bitset_container_t *container) {
    (void)container;
    return BITSET_CONTAINER_SIZE_IN_WORDS * sizeof(uint64_t);
}`

**Comment by lemire** [comment]
This is how the function is defined. It is the amount of bytes we need during serialization. There is a portable roaring format that relies on this definition. We have a Java and a Go implementation. They all use cardinality times 2 bytes. 

The bitset container use the correct amount of memory as well.

Please see...

https://github.com/RoaringBitmap/RoaringFormatSpec

**Comment by helifu** [comment]
Thanks for the quick response.
We are going to introduce CRoaring in our project, but first of all we need to figure out the memory consumption. It seems that 'void roaring_bitmap_statistics()' is a suitable api for us. 
And we know that 'size_t roaring_bitmap_size_in_bytes/roaring_bitmap_portable_size_in_bytes' returns the amount of bytes during serialization.
So, are we getting memory consumption right? Thanks in advance:)

**Comment by lemire** [comment]
There is a roaring_bitmap_shrink_to_fit function which ensures that size and capacity are identical. This being said, the gap between the two is probably not something that should concern you. In practice, the statistics function should give you an accurate estimate.

If you get good numbers with this function, then you should do well.

**Comment by helifu** [comment]
All right, thanks for your patient explanation, Professor Daniel. ^_^
