### ISSUE TITLE
C++ contains() can return std::optional<iterator>

### ISSUE THREAD

**Issue by tower120** [RoaringBitmap/CRoaring#206]
In C++ interface. Can `contains()` return `std::optional<iterator>` instead of just bool?

I want to iterate only certain subset of bitmap:
```cpp
Roaring bitset;

Roaring::iterator from = *bitset.contains(start_index);
Roaring::iterator to   = bitset.end();

for(std::size_t i : std::iterator_range(from, to)){
    // ...
}
```

**Comment by lemire** [comment]
We have the necessary infrastructure in C to support this efficiently. 

Would you consider submitting a PR to resolve this issue? I can help by pointing at the relevant C code.

**Comment by tower120** [comment]
> I can help by pointing at the relevant C code.

Please do.

> Would you consider submitting a PR to resolve this issue? 

I just test it performance-wise now. If it will suite my use-case, maybe...

---

I must point out that Roaring class interface is completely standard non-conformant.

For example, `isEmpty` must be called `empty`; `cardinality` - `size`; `remove` - must be `erase` and have overloaded versions for both key and iterator; `removeChecked` - probably not needed at all - it is safe to return bool always - compiler will optimize unused return.

That's not just matter of taste - it can not be used as replacement for `std::vector<bool>`, or with std algorithms.

Plus everything public.

**Comment by lemire** [comment]
I am sure the API can be improved. If you have proposals and you can preserve backward compatibility), then please issue a PR.

> removeChecked - probably not needed at all

Can you emulate the same functionality with the same or better performance after removing this function?

> it can not be used as replacement for std::vector<bool>, or with std algorithms.

Std algorithms are not aware of the performance characteristics of Roaring. If one relies on std algorithms with a Roaring object, one might get terrible performance.  If you do propose an improved C++ API, please include benchmarking code. 

The API is meant to reflect how the object should be used. It is possible, even quite certain, that it can be improved, but it is not good to dissociate the API from the performance characteristics.

**Comment by lemire** [comment]
```C
bool roaring_move_uint32_iterator_equalorlarger(roaring_uint32_iterator_t *it, uint32_t val) ;
```

That's the C function that provides the functionality you seek. All you need is to provide the proper C++ wrapping around it. (When I say "all you need", I don't mean to dismiss the work involved. I mean that one does not need to know the insides of the data structure.)

**Comment by tower120** [comment]
>  and you can preserve backward compatibility

I don't think it can be backward compatible (due to names). What about making new class in separate namespace? Like `namespace RoaringBitmap::cpp17{ class Roaring; }`.

> Can you emulate the same functionality with the same or better performance after removing this function?

I meant following:
 * remove current `bool remove()`
 * `bool removeChecked()` rename to `bool remove()` 

IOW, just return bool always, as std containers do (`std::vector::erase()` always return iterator, compiler elide everything related to unused return value).

> bool roaring_move_uint32_iterator_equalorlarger(roaring_uint32_iterator_t *it, uint32_t val) ;

Thanks.

**Comment by lemire** [comment]
> What about making new class in separate namespace?

Or just a new class name. That would be good.

We would prefer not to break backward compatibility for obvious reasons. However, adding code is fine. It increases our maintenance cost, but if there are good tests, it is fine.


Note: though I am not the sole author of the C++ wrapper, I will gladly take the blame for how it is not very "STL like". You make good points.

**Comment by lemire** [comment]
Don't forget that we want to assess the performance effect of any new API.

If someone does not care for performance, then there are already good containers in STL that do a fine job. The motivation for using Roaring is mostly performance, so performance is critical. (It is not at the expense of everything else, just something we cannot dismiss.)

**Comment by tower120** [comment]
> Or just a new class name. That would be good.

No matter what, there MUST be at least some namespace to prevent name-clashes with user-space.

With new class name instead of new namespace for new api version, you'll have to rename any old api related global functions too. That's c way, not c++.

> If someone does not care for performance, then there are already good containers in STL that do a fine job. 

That's biased.

**Comment by lemire** [comment]
> That's biased.

Yes. We have a bias for performance.

**Comment by tower120** [comment]
Sorry, intialy I thought I'll need that (for custom ECS). But then I switched for archetype-based ECS, and there where no need for bitmaps anymore...

**Comment by lemire** [comment]
Ok. I will close this issue.

Note that CRoaring is a C library. We provide a thin C++ wrapper that calls the C functions. One can easily design their own C++ classes. People do not need to use our C++ wrapper.
