### ISSUE TITLE
Wrong value returned by roaring_bitmap_rank

### ISSUE THREAD

**Issue by Ezibenroc** [RoaringBitmap/CRoaring#208]
The function `roaring_bitmap_rank` sometimes return wrong values. Here is an example, name it `test.c`.
Note that the bug does not appear if you change the upper bound or the step of the loop.
```c
#include <stdio.h>
#include "roaring.c"

int main() {
    roaring_bitmap_t *r = roaring_bitmap_create();
    for (uint32_t i = 1; i < 8194; i+=2) {
        roaring_bitmap_add(r, i);
    }
    uint32_t rank = roaring_bitmap_rank(r, 63);
    printf("rank: %u\n", rank);
    assert(rank == 32);
    return 0;
}
```

Compile and run:
```sh
bash amalgamation.sh &&  cc -march=native -O3 -std=c11  -o test test.c  && ./test
```
The returned rank is 64 instead of 32.

It seems that this error was introduced by commit 0b4d9df2fdc063d923ad2ed8e9a43e8215f132dd.

**Comment by lemire** [comment]
Squarely my fault. Fixed in latest commit.

**Comment by aqrit** [comment]
This functions seems a little tortured.
I'm sure no one cares, and I haven't tested it but...
compare to: 
```
/* Returns the number of values equal or smaller than x */
int bitset_container_rank(const bitset_container_t *container, uint16_t x) {
  int sum = 0;
  int i = 0;
  for (int end = x / 64; i < end; i++){
    sum += hamming(container->array[i]);
  }
  uint64_t lastword = container->array[i];
  uint64_t lastpos = UINT64_C(1) << (x % 64);
  uint64_t mask = lastpos + lastpos - 1; // smear right
  sum += hamming(lastword & mask);
  return sum;
}
```

**Comment by lemire** [comment]
@aqrit   This looks better than my tortured version, you are right.

**Comment by aqrit** [comment]
The current version has an out-of-bounds read when `x == 0xFFFF`

The version I posted above seems to be correct. 
It also avoids an unnecessary call to `hamming()` on some numbers (e.g. 63)

**Comment by aqrit** [comment]
*correct = does the same as the current version.
which more or may not be correct...

**Comment by lemire** [comment]
Yes... thank you... I think your code is better, I'll do something with it in a few hours. Thanks again.
