### ISSUE TITLE
May function bitset_bitset_container_intersection_inplace call bitset_container_and directely ?

### ISSUE THREAD

**Issue by hk53315** [RoaringBitmap/CRoaring#209]
To avoid mass but none necessary '&' operation, We can call bitset_container_and once, But call bitset_container_and_justcard and bitset_container_and_nocard.

**Comment by lemire** [comment]
Can you elaborate? Maybe with code samples?

**Comment by lemire** [comment]
I am going to close this issue. Reporter should reopen with more details.
