### ISSUE TITLE
Implement Not function in C++ wrapper?

### ISSUE THREAD

**Issue by hk53315** [RoaringBitmap/CRoaring#210]
just like roaring_bitmap_not.

**Comment by lemire** [comment]
I guess that you mean in the C++ wrapper, right?

Pull request invited.

**Comment by kiarashgl** [comment]
I think that the clear() function isn't implemented in the C++ wrapper too. We should use it like this:
`roaring_bitmap_clear(&bitset.roaring);`
Is this correct?

**Comment by lemire** [comment]
Right...

**Comment by gpyalt** [comment]
isn't this the "not"?

```
    void flip(uint64_t range_start, uint64_t range_end) {
        roaring_bitmap_flip_inplace(&roaring, range_start, range_end);
    }
```

**Comment by lemire** [comment]
It is.

**Comment by gpyalt** [comment]
So I guess this issue can be closed. I don't think clear() is really needed, as if we want to clear the bitmap x we can do `Roaring().swap(x)`, right?

**Comment by lemire** [comment]
It would still be nice to have an actual "clear" function, but I guess that you are right. Closing.
