### ISSUE TITLE
function name aligned_malloc, etc collides with other libraries

### ISSUE THREAD

**Issue by bdon** [RoaringBitmap/CRoaring#211]
The defined `aligned_malloc` function https://github.com/RoaringBitmap/CRoaring/blob/master/include/roaring/portability.h#L188 can conflict with other libraries that also provide portability headers. 

In my case I'm using S2 Geometry which also provides a `port.h` defining this function: https://github.com/google/s2geometry/blob/master/src/s2/base/port.h#L892

I am not an expert on writing portable C code, is there a workaround here other than creating multiple compilation units?

**Comment by lemire** [comment]
We could replace aligned_malloc by roaring_bitmap_aligned_malloc throughout. Would that be fine?

**Comment by bdon** [comment]
Yes, that solution would work for me.

**Comment by lemire** [comment]
Would you be willing to issue a PR implementing this approach? It is mostly search and replace but you could also verify that it solves your issue.

**Comment by bdon** [comment]
Yes, I'd be glad to!

**Comment by lemire** [comment]
Please do!

**Comment by lemire** [comment]
Closed via https://github.com/RoaringBitmap/CRoaring/pull/212
