### ISSUE TITLE
max size per integer in C/C++ implementation 

### ISSUE THREAD

**Issue by bseiller** [RoaringBitmap/CRoaring#214]
The FAQ of the Java implementation (https://github.com/RoaringBitmap/RoaringBitmap#faq) states
> That is, given a fixed overhead for the universe size (x), Roaring bitmaps never use more than 2 bytes per integer. You can call RoaringBitmap.maximumSerializedSize for a more precise estimate.

Is this true for the C/C++ implementation as well?

**Comment by lemire** [comment]
It is exactly the same format, the same data structure, so you should expect comparable memory usage. If you call `roaring_bitmap_portable_size_in_bytes`, it will give you the exact same answer as Java (as per the specification).

This extends to the Go implementation as well. They are interoperable versions of the same data structure.

Reopen if this does not answer your question.

**Comment by bseiller** [comment]
Thanks for the fast response!
