### ISSUE TITLE
What are best practices concerning performance and memory footprint while adding values?

### ISSUE THREAD

**Issue by bseiller** [RoaringBitmap/CRoaring#215]
As stated in the title, I'm wondering what are the best practices to fast/efficiently add a lot of values while keeping the memory footprint in check. I couldn't find any explicit guide. But I pieced together the following:
- Adding ordered values is faster than unordered values - this one could be concluded by inverting the statement concerning "random-looking data".
- Using addMany is faster than add (single) - found in the header file.
- calling runOptimize and shrinkToFit often **seems** to help keeping the memory footprint smaller/more stable than only calling it once at the end of the value-adding-phase, but calling it to often kills performance - via testing.
- does using roaring_bitmap_create_with_capacity with the final needed capacity make any difference concerning performance and/or allocated memory? - found in the header file

Are there any other ways to improve performance while not burning through **additional** memory during the value-adding-phase?

To give some context:
In my program, there are multiple bitmaps, each models another attribute, so the same value in two different bitmaps means the associated object has both those attributes. 
This also means all bitmaps share the same universe size of 16908544. 
Values are being added via addMany in batches up to the size of 256, but might be sparse, so less than 256 might be added with one call. 
runOptimize and shrinkToFit is currently being called after multiples of 2^16.

Any help is appreciated - also if there are code sample to look at or any other resources.

**Comment by lemire** [comment]
Benchmark shrinkToFit to see if it helps. I suggest it may not.

I suggest you look at the result of the run optimization, it might be improving some bitmaps and not others... 

The capacity construction with something like 260 might help. 

You absolutely want addMany as it will be faster and use less memory if it is a convenient function for you.

**Comment by bseiller** [comment]
Thank you again for another fast response!

Your suggestions/predictions were pretty spot on:
- shrinkToFit does not seem to make a real difference in my scenario, neither performance- nor memory-wise in either way.
- runOptimize (called after every chunk which coincides with the internal batch size of my program) on the other hand helps to keep the growth of the memory foot print in check nicely.
- capacity construction also does not make a relevant difference.
- addMany though was key to speed up the insertion-phase massively.

Thanks again!
