### ISSUE TITLE
CoW bug caused by counter of shared_container_t

### ISSUE THREAD

**Issue by nptai** [RoaringBitmap/CRoaring#216]
As I see, shared_container_t.counter is not counted atomically.

**Comment by lemire** [comment]
CRoaring does not promise thread-safety...
https://github.com/RoaringBitmap/CRoaring#thread-safety

**Comment by lemire** [comment]
The documentation (README) specifically state: "One should probably avoid the use of the copy-on-write attribute in a threaded environment."
