### ISSUE TITLE
Double-free exceptions occurs when call removeRunCompression of class roaring64map

### ISSUE THREAD

**Issue by hurricane1026** [RoaringBitmap/CRoaring#220]
the test case is in [PR219](https://github.com/RoaringBitmap/CRoaring/pull/219).
this issue only occurs in CopyOnWrite is true then calling removeRunCompression.

**Comment by hurricane1026** [comment]
239 	    container->counter--;
   240 	    if (container->counter == 0) {
   241 	        assert(container->typecode != SHARED_CONTAINER_TYPE_CODE);
-> 242 	        container_free(container->container, container->typecode);
   243 	        container->container = NULL;  // paranoid
   244 	        free(container);
   245 	    }
Target 0: (cpp_unit) stopped.
(lldb) image lookup -n container_free
1 match found in /Users/hurricane/private/code/cpp/CRoaring/build/libroaring.0.dylib:
        Address: libroaring.0.dylib[0x000000000001eac0] (libroaring.0.dylib.__TEXT.__text + 120496)
        Summary: libroaring.0.dylib`container_free at containers.c:25

**Comment by hurricane1026** [comment]
the exception will occurs in container_free function.

**Comment by lemire** [comment]
Fixed. Thanks for the report.
