### ISSUE TITLE
container_add() cause memory leak

### ISSUE THREAD

**Issue by nptai** [RoaringBitmap/CRoaring#227]
``` c++
// include/roaring/containers/containers.h:472
static inline void *container_add(void *container, uint16_t val,
                                  uint8_t typecode, uint8_t *new_typecode) {
    container = get_writable_copy_if_shared(container, &typecode);
    switch (typecode) {
...
        case ARRAY_CONTAINER_TYPE_CODE: {
            array_container_t *ac = (array_container_t *)container;
            if (array_container_try_add(ac, val, DEFAULT_MAX_SIZE) != -1) {
                *new_typecode = ARRAY_CONTAINER_TYPE_CODE;
                return ac;
            } else {
                bitset_container_t* bitset = bitset_container_from_array(ac);
                bitset_container_add(bitset, val);
                *new_typecode = BITSET_CONTAINER_TYPE_CODE;
                return bitset;
            }
        } break;
...
```
In case: `container` is cloned and `bitset_container_t* bitset` is created, cause leaks `array_container_t* ac` (`container`).

**Comment by lemire** [comment]
The line... `array_container_t *ac = (array_container_t *)container` does allocate memory so it cannot create a leak. If you think that there is a memory leak in the library, please provide a reproducible case where the leak occurs. We can then verify the leak.

**Comment by nptai** [comment]
I means who is owner of cloned `container` if that function returns `bitset`

**Comment by lemire** [comment]
We run tests with memory sanitizers. If you think that there is a memory leak, please provide a test case where we can verify a memory leak.

**Comment by lemire** [comment]
> I means who is owner of cloned container if that function returns bitset

There is no cloning involved in this function. I think you mistakenly think that `array_container_t *ac = (array_container_t *)container` allocates memory. It does not.

**Comment by nptai** [comment]
I've just realized container passing this function is not a share_container (ra_unshare_container_at_index called before). Thank you.
