### ISSUE TITLE
Setting up boolean set variables

### ISSUE THREAD

**Issue by flipchart** [RoaringBitmap/CRoaring#229]
I want to use Roaring for manipulating canonical sum of products (SoP) boolean sets, but setting up the initial values takes too long since I need 64 variables (which requires adding numbers to the set through to 2^64 for each variable). Example with 4 variables:

Truth table for 4 variables

n3 | n2 | n1 | n0 | Boolean set index
-- | -- | -- | -- | --
0 | 0 | 0 | 0 | 0
0 | 0 | 0 | 1 | 1
0 | 0 | 1 | 0 | 2
0 | 0 | 1 | 1 | 3
0 | 1 | 0 | 0 | 4
0 | 1 | 0 | 1 | 5
0 | 1 | 1 | 0 | 6
0 | 1 | 1 | 1 | 7
1 | 0 | 0 | 0 | 8
1 | 0 | 0 | 1 | 9
1 | 0 | 1 | 0 | 10
1 | 0 | 1 | 1 | 11
1 | 1 | 0 | 0 | 12
1 | 1 | 0 | 1 | 13
1 | 1 | 1 | 0 | 14
1 | 1 | 1 | 1 | 15

Corresponding boolean set index values for canonical SoP form for each variable:

  |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --
n0 | 1 | 3 | 5 | 7 | 9 | 11 | 13 | 15
n1 | 2 | 3 | 6 | 7 | 10 | 11 | 14 | 15
n2 | 4 | 5 | 6 | 7 | 12 | 13 | 14 | 15
n3 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15

So I'd like to generate the bitmaps for 64 variables, but you can see that this is infeasible. Since each variable has a repeating pattern, is it possible to create a bitmap faster by encoding the repeating pattern?

**Comment by lemire** [comment]
This issue has been opened since June. I am going to close it. If you have features that you'd like to see, it would be best if you considered creating a pull request or, at least, describing it precisely. Your issue seems open ended.
