### ISSUE TITLE
c(not c++) support for 64-bit integers

### ISSUE THREAD

**Issue by lambgong** [RoaringBitmap/CRoaring#232]

**Comment by lemire** [comment]
This could be achieved inexpensively by wrapping the C++ API with a C API.

Pull requests invited.

**Comment by guymolinari** [comment]
I do have a partial implementation of the BSI library.   Will PR it in the next few weeks.

**Comment by madscientist** [comment]
Is this different from issue #1?

**Comment by lemire** [comment]
Quite right. This is a duplicate. Closing in favour of https://github.com/RoaringBitmap/CRoaring/issues/1

**Comment by lemire** [comment]
Note that this is supported already via the C++ interface. The core C code is 32-bit only, by design.
