### ISSUE TITLE
SIGILL in **roaring_bitmap_get_cardinality** method

### ISSUE THREAD

**Issue by anthonylouisbsb** [RoaringBitmap/CRoaring#234]
I have a Java program that calls the the CRoaring library by JNI API.

When the program calls the **roaring_bitmap_get_cardinality** a `SIGILL` error is thrown:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007f3bf5836625, pid=26, tid=0x00007f3bea5d9700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_221-b11) (build 1.8.0_221-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.221-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libroaring.so+0x22625]  roaring_bitmap_get_cardinality+0x45
#
# Core dump written. Default location: /simbiose/data/shannondb/core or core.26
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  T H R E A D  ---------------

Current thread (0x00007f3c4c5f3000):  JavaThread "Worker-qresult-0" daemon [_thread_in_native, id=239, stack(0x00007f3bea4d9000,0x00007f3bea5da000)]

siginfo: si_signo: 4 (SIGILL), si_code: 2 (ILL_ILLOPN), si_addr: 0x00007f3bf5836625
```

We compiled the library using these steps:
- cmake -DROARING_DISABLE_AVX=ON -DROARING_DISABLE_NATIVE=ON -DROARING_DISABLE_X64=ON 
- make 
- sudo make install

The computer processor is an **Intel Pentium G4560**.

When I repeat those steps in a **Core i5-5200u** everything works fine.

Can you help us with this issue?

**Comment by lemire** [comment]
My first reaction is that this is likely to be a problem upstream, probably in your build setup.

Can you do the following...

```
$ cd some_directory_of_your_choosing
$ cmake put_here_directory_where_croaring_is
$ cmake --build . --verbose
$ ctest --output-on-failure
```

It should work fine even on old processors. Post the complete output.


(Make sure you have a 'recent' cmake so that my instructions work.)

**Comment by lemire** [comment]
For people reading this, the G4560 is a low-cost processor with its AVX component disabled. Currently, CRoaring does not do runtime dispatching. So if you compile with AVX instructions enabled, the code is likely to use AVX instructions. However, CRoaring is built (by default) without AVX instructions... so there should be no problem.

**Comment by lemire** [comment]
Submitter should resubmit an issue with clarification. 

Closing.
