### ISSUE TITLE
multiple definition of `roaring_bitmap_get_copy_on_write'; 

### ISSUE THREAD

**Issue by Flians** [RoaringBitmap/CRoaring#237]
Hi,
I use the CRoaring as a static library. But I meet some problem.
I compile the CRoaring with the command:
`
add_library(croaring STATIC ${PROJECT_SOURCE_DIR}/include/CRoaring/roaring.c)
`

![image](https://user-images.githubusercontent.com/16850481/91840735-c056b400-ec83-11ea-8085-a789117579ba.png)
And there are some errors:
```
d:/programfiles/mingw/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: libcroaring.a(roaring.c.obj): in function `roaring_bitmap_get_copy_on_write':E:/workplace/vs_workplace/GraphQuery/include/CRoaring/roaring.h:6503: multiple definition of `roaring_bitmap_get_copy_on_write'; CMakeFiles/GraphQuery.dir/objects.a(main.cpp.obj):E:/workplace/vs_workplace/GraphQuery/include/CRoaring/roaring.h:6503: first defined here
d:/programfiles/mingw/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: libcroaring.a(roaring.c.obj): in function `roaring_bitmap_set_copy_on_write':E:/workplace/vs_workplace/GraphQuery/include/CRoaring/roaring.h:6506: multiple definition of `roaring_bitmap_set_copy_on_write'; CMakeFiles/GraphQuery.dir/objects.a(main.cpp.obj):E:/workplace/vs_workplace/GraphQuery/include/CRoaring/roaring.h:6506: first defined here
d:/programfiles/mingw/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: libcroaring.a(roaring.c.obj): in function `roaring_bitmap_add_range':        
E:/workplace/vs_workplace/GraphQuery/include/CRoaring/roaring.h:6726: multiple definition of `roaring_bitmap_add_range'; CMakeFiles/GraphQuery.dir/objects.a(match.cpp.obj):E:/workplace/vs_workplace/GraphQuery/include/CRoaring/roaring.h:6726: first defined here
```
Finally, I find the solution. The following codes in roaring.c needs to be commented.
```
extern inline bool roaring_bitmap_get_copy_on_write(const roaring_bitmap_t* r);
extern inline void roaring_bitmap_set_copy_on_write(roaring_bitmap_t* r, bool cow);

extern inline void roaring_bitmap_add_range(roaring_bitmap_t *ra, uint64_t min, uint64_t max);
```
You can check it.

**Comment by lemire** [comment]
You want to use CRoaring from CMake, by using the single-header CRoaring build while having CMake turn the single-header build into a static library.

You will find an example at this repository...
https://github.com/RoaringBitmap/croaring_cmake_demo_from_single_header


Define the library in CMake as follows...

```CMake
add_library(croaring STATIC ${PROJECT_SOURCE_DIR}/dependencies/croaring/roaring.c)
target_include_directories(croaring PUBLIC ${PROJECT_SOURCE_DIR}/dependencies/croaring/)
```

Then link it as follows...

```CMake
add_executable(test test.c) 
target_link_libraries(test croaring) 
```

Use a simple C file such as this one...

```C
#include <stdio.h>
#include "roaring.h"

int main() {
  roaring_bitmap_t *r1 = roaring_bitmap_create();
  for (uint32_t i = 100; i < 1000; i++) roaring_bitmap_add(r1, i);
  printf("cardinality = %d\n", (int) roaring_bitmap_get_cardinality(r1));
  roaring_bitmap_free(r1);
  return 0;
}
```

Note that you should not include `roaring.c` if you are already linking to CRoaring as a static library.


> And there are some errors:

These errors indicate that you have multiple definitions of some functions. But, of course, we only define the functions once. So if you have multiple definitions, it tells you that you compiled the code twice.


Given that you do not provide a reproducible case, it is not possible for me to tell you exactly where your error is,  but you almost surely made an error somewhere. Maybe you include the `roaring.c` file as a header file while also linking to a static CRoaring library.

In any case, please follow the link above for a working and well tested example.

I am closing this. If you think I am wrong, please reopen with a reproducible example and a detailed analysis.
