### ISSUE TITLE
Flips make huge unoptimizable results for very low entropy data

### ISSUE THREAD

**Issue by AE1020** [RoaringBitmap/CRoaring#241]
I tried swapping roaring bitmaps in for a weak bitmap implementation in a project...hoping it would handle negated bitsets better.  When I did, things slowed down dramatically.  It seems negation generates huge structures on very simple examples.

Compression seems to not help at all.  The size is pegged at 65536, which is not in bytes but a count of container pointers...with those containers each having their own mallocs.  :-/

Here's some output from a test program (code attached below):

```
R BEFORE FULL FLIP
[ 3 4 ]
size = 1
allocation_size = 2

FULL FLIP RESULT R2
[ 0 1 2 5 6 7 8 9 10 11 ... ]
size = 65536
allocation_size = 65536

AFTER RUN OPTIMIZE R2:
[ 0 1 2 5 6 7 8 9 10 11 ... ]
size = 65536
allocation_size = 65536

AFTER SHRINK TO FIT R2:
[ 0 1 2 5 6 7 8 9 10 11 ... ]
size = 65536
allocation_size = 65536

FULL INPLACE FLIP RESULT R:
[ 0 1 2 5 6 7 8 9 10 11 ... ]
size = 65536
allocation_size = 65536

AFTER RUN OPTIMIZE R:
[ 0 1 2 5 6 7 8 9 10 11 ... ]
size = 65536
allocation_size = 65536

AFTER SHRINK TO FIT R:
[ 0 1 2 5 6 7 8 9 10 11 ... ]
size = 65536
allocation_size = 65536
```

Code for `fliptest.c`, using the Unity build at [`067b46`](https://github.com/lemire/CRoaringUnityBuild/commit/067b4b68545b1d2e21224e9ad3e4740b34f35a12).  I tried some older builds to see if it was a regression, but the earliest build I could get to work with flipping at all had similar results (slightly larger `allocation_size` for the flips, which the compression dropped to 65536).

```
#include <stdio.h>
#include "roaring.h"
#include "roaring.c"

inline static roaring_bitmap_t *roaring_bitmap_fully_flip(
    roaring_bitmap_t *r
){
    uint64_t bignumber = UINT64_C(0x100000000);
    return roaring_bitmap_flip(r, 0, bignumber);
}

inline static void roaring_bitmap_fully_flip_inplace(
    roaring_bitmap_t *r
){
    uint64_t bignumber = UINT64_C(0x100000000);
    roaring_bitmap_flip_inplace(r, 0, bignumber);
}

bool dump_one(uint32_t value, void *param) {
    int *limit = (int*)(param);
    if (*limit == 0) {
       printf("... ");
       return false;
    }
    --*limit;
    printf("%d ", value);
    return true;
}

void dump(const char* label, roaring_bitmap_t *r) {
    printf("%s\n", label);

    int max = 10;
    printf("[ ");
    roaring_iterate(r, &dump_one, &max);
    printf("]\n");

    roaring_array_t *ra = &r->high_low_container;
    printf("size = %d\n", ra->size);
    printf("allocation_size = %d\n", ra->allocation_size);
    printf("\n");
}

int main(void) {
    roaring_bitmap_t *r = roaring_bitmap_of(2, 3, 4);
    dump("R BEFORE FULL FLIP", r);

    roaring_bitmap_t *r2 = roaring_bitmap_fully_flip(r);
    dump("FULL FLIP RESULT R2", r2);

    roaring_bitmap_run_optimize(r2);
    dump("AFTER RUN OPTIMIZE R2:", r2);

    roaring_bitmap_shrink_to_fit(r2);
    dump("AFTER SHRINK TO FIT R2:", r2);

    roaring_bitmap_fully_flip_inplace(r);
    dump("FULL INPLACE FLIP RESULT R:", r);

    roaring_bitmap_run_optimize(r);
    dump("AFTER RUN OPTIMIZE R:", r);

    roaring_bitmap_shrink_to_fit(r);
    dump("AFTER SHRINK TO FIT R:", r);

    roaring_bitmap_free(r);
    roaring_bitmap_free(r2);
}
```

**Comment by AE1020** [comment]
Looking closer at the code, I'm gathering that despite the presence of a flip operation in the API, there is nothing in the containers that are "flip-aware" and thus unable to take advantage of "negative information" when compressing/optimizing.  :-/

**Comment by lemire** [comment]
> Hence one must decide if one's information tends to be in the negative, and if so invert the result at a higher level.

That is correct.


If someone wants to produce code that handles "negated bitmaps" that would certainly be doable... and we would take such a pull request eagerly. But meanwhile, it is up to you.

We have no support for "constant-time flipping" or "highly efficient flipping". There is no such thing documented anywhere in our code. 

I am going to close this.
