### ISSUE TITLE
Deserialized bitmap does not match original one in some cases

### ISSUE THREAD

**Issue by azhang7** [RoaringBitmap/CRoaring#245]
Certain sequences of bitmap operations in roaring can cause it to produce a bitmap that is written in a way that it cannot be read back correctly.

The sequence is as follows:
1. Create a roaring container as a run.
2. Add 2047 individual non-contiguous bits to the container.
3. Add one more individual non-contiguous bit to that same container.
4. Serialize the bitmap.
5. Deserialize the bitmap.
6. Compare the two bitmaps.

Without step 3, the bitmaps match. However, they do not match if step 3 is included. [Gist demonstrating this issue.](https://gist.github.com/azhang7/d16295a79d7ebde01bee337f0e04de97)

The reason appears to be because roaring's portable bitmap does not store the container type. Instead it relies on the number of elements in the container to determine its type [1]. This logic works for arrays that are converted to bitsets, which happens at 4096 entries (the value of DEFAULT_MAX_SIZE [2]). This doesn't hold for runs though, because the conversion happens based on memory footprint. So a run container with more than 2048 runs, but cardinality less than 4096 creates this issue.

[1] https://github.com/RoaringBitmap/CRoaring/blob/0ba6a76d0d5bd26be50cbdcb80fce0fb0598b9d6/src/roaring_array.c#L819
[2] https://github.com/RoaringBitmap/CRoaring/blob/0ba6a76d0d5bd26be50cbdcb80fce0fb0598b9d6/include/roaring/containers/array.h#L17

**Comment by lemire** [comment]
The bug is real, but it does not look like it is a serialization bug. As per our format, there should not be a bitset container with so few values.

**Comment by lemire** [comment]
Ok. I have a fix.

The issue is that in rare cases, the run container would need to be converted into an array container whereas we wrongly assumed that it was always converted into a bitset container. It is sufficient to add a check and correct the type when this occurs.

Thanks for reporting the issue!!!

**Comment by azhang7** [comment]
That was fast. Thanks for the fix.
