### ISSUE TITLE
Amazon server issue

### ISSUE THREAD

**Issue by ancuop** [RoaringBitmap/CRoaring#26]
Hi Lemire,

I'm interested in CRoaring and tried to apply it to my project on amazone server however it causes "illegal instruction" error. 
I found that the server does not satisfy the CRoaring requirement. 
(Amazone server uses: Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz) 

Could you teach me how to use CRoaing in this case or do you have any trick?
Thank you very much.

**Comment by fsaintjacques** [comment]
http://ark.intel.com/products/81706/Intel-Xeon-Processor-E5-2660-v3-25M-Cache-2_60-GHz says that is supports AVX2. Could you run `cat /proc/cpuinfo | grep avx | head -1`? croaring is written with AVX2 in mind, we might back-port it to AVX one day, but it is not in the current implementation.

**Comment by lemire** [comment]
It might be possible, already, to run CRoaring on old processors, try ``cmake -DAVX_TUNING=OFF``.

It may or may not work. It is entirely untested.

**Comment by fsaintjacques** [comment]
@lemire last time I checked, it didn't compile.

**Comment by lemire** [comment]
@fsaintjacques I'll open an issue.

**Comment by lemire** [comment]
@ancuop  I am going to close this as it is explicitly documented that we do not support old hardware.


https://github.com/RoaringBitmap/CRoaring#requirements

Nevertheless, supporting legacy hardware is a sensible target, so I have opened an issue...

https://github.com/RoaringBitmap/CRoaring/issues/27

I am sorry, but we basically do not have the resources to do everything. What we would need is for developers to help out. If you are interested in digging in the code and submitting pull requests, please do.

**Comment by lemire** [comment]
@ancuop  If you do find out that your hardware supports the necessary instructions, you should make sure that your software does. Typically, an "illegal instruction" error suggests that either the hardware or the software does not support the instruction. 

If you have more information for us, feel free to re-open the issue.

**Comment by ancuop** [comment]
@lemire , @fsaintjacques,

Thank you for your information and support. Hope #27 will be fixed soon!
 Have a nice week!

**Comment by lemire** [comment]
@ancuop 

Thanks.
