### ISSUE TITLE
Project should build and run on non-Intel 64-bit processors (e.g., ARM)

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/CRoaring#27]
It should be possible to run this code on a machine with a non-Intel CPU.

**Comment by fsaintjacques** [comment]
Can we relax the constraint to require at least AVX?

**Comment by lemire** [comment]
Anything would be better than our strict requirements.


 But ultimately, we might like to support non-x64 processor. I'd love to run tests on my Raspberry Pi 3 (with Neon). Whether this needs to be supported in this library, I don't know.

**Comment by fsaintjacques** [comment]
For reference, I'm adding 2 links that talk about dynamic binding:

- https://stackoverflow.com/questions/29524200/how-to-do-runtime-binding-based-on-cpu-capabilities-on-linux
- https://stackoverflow.com/questions/34027468/can-i-make-shared-library-constructors-execute-before-relocations

**Comment by lemire** [comment]
@ancuop @fsaintjacques 

It should now be possible to build this without AVX support with ``cmake -DAVX_TUNING=OFF``.

**Comment by lemire** [comment]
Fixed as per https://github.com/RoaringBitmap/CRoaring/commit/972f6c1112277148310301561987ef314db0035b

**Comment by Ezibenroc** [comment]
The compilation of the library fails on some machines, I have the following error:

```
/home/tom/CRoaring/src/array_util.c: In function ‘store_unique’:
/home/tom/CRoaring/src/array_util.c:941:5: warning: implicit declaration of function ‘_pext_u32’ [-Wimplicit-function-declaration]
```

I also have a lot of these warnings:
```
In file included from /home/tom/CRoaring/src/containers/containers.c:2:0:
/home/tom/CRoaring/src/containers/containers.c: In function ‘container_printf’:
/home/tom/CRoaring/include/containers/containers.h:63:28: warning: inlining failed in call to ‘container_unwrap_shared.part.0’: call is unlikely and code size would grow [-Winline]
/home/tom/CRoaring/src/containers/containers.c:14:6: warning: called from here [-Winline]
```

It happens on two different machines:
* A "compute server":
   - Linux 3.2 (Debian 7)
   - gcc 4.7.2
   - CPU Intel Xeon E5-2430L
* A classical DELL desktop:
   - Linux 3.13 (Ubuntu 14.04)
   - gcc 4.8.4
   - CPU Intel Core i3-3245

I know these are quite old. Is there any hope to make CRoaring useable on them?

**Comment by lemire** [comment]
Sure, we can add more checks. 


I'll get back to you.

**Comment by lemire** [comment]
@Ezibenroc  Try with the latest commit. The following should work:

```
rm -r -f release
mkdir release
cd release
cmake ..
make
make test
```

I have made it so that it tries to detect AVX2 and BMI2 support without you having to do anything.

Closing for now, reopen if this fails.

**Comment by Ezibenroc** [comment]
Thanks for your help. It fixed the compilation on the second machine, but not on the first one.
Now, the error is that `UINT64_C` and `UINT32_C` are not defined. I fixed it with https://github.com/RoaringBitmap/CRoaring/pull/40
