### ISSUE TITLE
with pedantic compiler flags, GCC warns that it is possible to try to allocate more memory than malloc would allow

### ISSUE THREAD

**Issue by davegomboc** [RoaringBitmap/CRoaring#278]
Encountering an issue in static bool realloc_array(roaring_array_t *ra, int32_t new_capacity) in roaring_array.c involving:

const size_t memoryneeded = new_capacity * (
            sizeof(uint16_t) + sizeof(container_t) + sizeof(uint8_t));
void *bigalloc = malloc(memoryneeded);

Note that the passed in value for new_capacity is being provided by ra_shrink_to_fit (internal Roaring code), not external code.

Here's the compilation error generated by g++-10 using -flto, -DNDEBUG (does not occur without -DNDEBUG):

In function 'realloc_array',
    inlined from 'realloc_array' at _deps/c_roaring-src/src/roaring_array.c:37:13,
    inlined from 'ra_shrink_to_fit' at _deps/c_roaring-src/src/roaring_array.c:96:10,
    inlined from <my code> as _deps/c_roaring-src/src/roaring.c:1308.15:
_deps/c_roaring-src/src/roaring_array.c:53:22: error: argument 1 range [18446744050087231488, 18446744073709551605] exceeds maximum object size 9223372036854775807 [-Werror=alloc-size-larger-than=]
   53 |     void *bigalloc = malloc(memoryneeded);

compilation terminated due to -Wfatal-errors.
lto1: all warnings being treated as errors
lto-wrapper: fatal-error: /usr/bin/g++-10 returned 1 exit status
compilation terminated.
/usr/bin/ld.gold: fatal error: lto-wrapper failed
collect2: error: ld returned 1 exit status

**Comment by lemire** [comment]
You have enabled pedantic static analysis which flags the fact that we may, in the course of the program, allocate more memory than malloc would allow.

This is not an error. It is a warning enabled by the fact that you are using pedantic static analysis.


@AE1020 have a look.

**Comment by davegomboc** [comment]
The code snippet above clearly shows that if new_capacity _were_ to have a small negative value (like -1), it would be multiplied by some low positive value like 4 (the sum of the sizeof() statements) to become -4, then sign-extended to 64-bits, then converted to unsigned, then passed to malloc, thus generating the diagnostic.  My understanding of the response is "well, it may be that the compiler hasn't proven that this actually happens: it merely just can't conclude that it doesn't happen".

You might be correct.  However, -Walloc-size-larger-than=PTRDIFF_MAX is included as part of -Wall in recent GCC versions, as discussed at https://developers.redhat.com/blog/2017/02/22/memory-error-detection-using-gcc/.  -Wall is an incredibly-often used flag, which alone strongly suggests to me that -Walloc-size-larger-than is not an option that is intended to ever issue false positives.  I certainly do not claim that GCC is bug-free in this regard, but it seems extremely likely to me that the compiler actually identified a code path where new_capacity actually has the value of a small-magnitude signed 32-bit value.

**Comment by lemire** [comment]
> However, -Walloc-size-larger-than=PTRDIFF_MAX is included as part of -Wall in recent GCC versions

GCC 10 is my current default compiler. CRoaring compiles with -Wall by default (plus a few more pedantic warnings). I compile CRoaring without warnings.

Let us look at the official documentation

https://gcc.gnu.org/onlinedocs/gcc-10.2.0/gcc/Warning-Options.html#Warning-Options

```
-Wall
This enables all the warnings about constructions that some users consider questionable, and that are easy to avoid (or modify to prevent the warning), even in conjunction with macros. This also enables some language-specific warnings described in C++ Dialect Options and Objective-C and Objective-C++ Dialect Options.

-Wall turns on the following warning flags:

-Waddress   
-Warray-bounds=1 (only with -O2)  
-Wbool-compare  
-Wbool-operation  
-Wc++11-compat  -Wc++14-compat  
-Wcatch-value (C++ and Objective-C++ only)  
-Wchar-subscripts  
-Wcomment  
-Wduplicate-decl-specifier (C and Objective-C only) 
-Wenum-compare (in C/ObjC; this is on by default in C++) 
-Wenum-conversion in C/ObjC; 
-Wformat   
-Wformat-overflow  
-Wformat-truncation  
-Wint-in-bool-context  
-Wimplicit (C and Objective-C only) 
-Wimplicit-int (C and Objective-C only) 
-Wimplicit-function-declaration (C and Objective-C only) 
-Winit-self (only for C++) 
-Wlogical-not-parentheses 
-Wmain (only for C/ObjC and unless -ffreestanding)  
-Wmaybe-uninitialized 
-Wmemset-elt-size 
-Wmemset-transposed-args 
-Wmisleading-indentation (only for C/C++) 
-Wmissing-attributes 
-Wmissing-braces (only for C/ObjC) 
-Wmultistatement-macros  
-Wnarrowing (only for C++)  
-Wnonnull  
-Wnonnull-compare  
-Wopenmp-simd 
-Wparentheses  
-Wpessimizing-move (only for C++)  
-Wpointer-sign  
-Wreorder   
-Wrestrict   
-Wreturn-type  
-Wsequence-point  
-Wsign-compare (only in C++)  
-Wsizeof-pointer-div 
-Wsizeof-pointer-memaccess 
-Wstrict-aliasing  
-Wstrict-overflow=1  
-Wswitch  
-Wtautological-compare  
-Wtrigraphs  
-Wuninitialized  
-Wunknown-pragmas  
-Wunused-function  
-Wunused-label     
-Wunused-value     
-Wunused-variable  
-Wvolatile-register-var  
-Wzero-length-bounds
Note that some warning flags are not implied by -Wall. Some of them warn about constructions that users generally do not consider questionable, but which occasionally you might wish to check for; others warn about constructions that are necessary or hard to avoid in some cases, and there is no simple way to modify the code to suppress the warning. Some of them are enabled by -Wextra but many of them must be enabled individually.

-Wextra
This enables some extra warning flags that are not enabled by -Wall. (This option used to be called -W. The older name is still supported, but the newer name is more descriptive.)

-Wclobbered  
-Wcast-function-type  
-Wdeprecated-copy (C++ only) 
-Wempty-body  
-Wignored-qualifiers 
-Wimplicit-fallthrough=3 
-Wmissing-field-initializers  
-Wmissing-parameter-type (C only)  
-Wold-style-declaration (C only)  
-Woverride-init  
-Wsign-compare (C only) 
-Wstring-compare 
-Wredundant-move (only for C++)  
-Wtype-limits  
-Wuninitialized  
-Wshift-negative-value (in C++03 and in C99 and newer)  
-Wunused-parameter (only with -Wunused or -Wall) 
-Wunused-but-set-parameter (only with -Wunused or -Wall)
The option -Wextra also prints warning messages for the following cases:

A pointer is compared against integer zero with <, <=, >, or >=.
(C++ only) An enumerator and a non-enumerator both appear in a conditional expression.
(C++ only) Ambiguous virtual bases.
(C++ only) Subscripting an array that has been declared register.
(C++ only) Taking the address of a variable that has been declared register.
(C++ only) A base class is not initialized in the copy constructor of a derived class.
```

**Comment by lemire** [comment]
You can verify in CI that we build without warnings under GCC 10:

https://github.com/RoaringBitmap/CRoaring/actions?query=workflow%3AUbuntu-GCC10-CI

**Comment by lemire** [comment]
I am going to close this. Compiling without warning under very pedantic is not a goal of this library. However, pull requests are invited if folks feel strongly about such warnings.
