### ISSUE TITLE
CodeChecker run with current checkout 

### ISSUE THREAD

**Issue by K2** [RoaringBitmap/CRoaring#282]
# CodeChecker used to run a mixed suite of static analysis

Many of these are for the unit/bench tools.  However there are some interesting results but the depth of the call chain's and intended API spec's I'm not sure on so I'm posting them if people want to take a look at the results.  They were are built against a fresh checkout from today.

[reports_html.tar.gz](https://github.com/RoaringBitmap/CRoaring/files/5728050/reports_html.tar.gz)

**Comment by lemire** [comment]
I am going to close this because I think we need to focus on tangible issues as opposed to potential issues.

**Comment by lemire** [comment]
If you do identify real problems, please open a specific issues describing the problem, or better yet, submit a pull request.
