### ISSUE TITLE
Implement custom memory allocators

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/CRoaring#284]
Some users need custom memory allocation (e.g., @olan-ibm). We want to provide such a functionality to our users but without making all users pay for increase memory usage or lower performance.

CRoaring is a C library and the preferred way in C to get custom memory allocation is to either pass functions or overwrite the default malloc/free. Furthermore, CRoaring has the concept of shared container, containers that can be part of several bitmaps.

Given that these users would like to have different bitmaps use different memory allocators, this means that we somehow need to trace memory allocation at the container level (bitmaps are made of small independent entities called containers) while resolving the conflict for shared containers if any.

One PR https://github.com/RoaringBitmap/CRoaring/pull/271 attempted to solve this issue by passing a roaring_options_t parameter which embeds, potentially a custom allocator, to every struct/class inside the bitmap instance where we might do dynamic allocation (including every container). It adds an overhead of 8 bytes per container, whether you need memory allocation or not. In that PR memory allocation is entirely determined at runtime, at the container level. This is a very potent model in the sense that anyone at any time can decide to start using one or several custom memory allocators.

The concern is that most people, most of the time, do not need custom memory allocation and when they do, they know about this time at compile time. The PR https://github.com/RoaringBitmap/CRoaring/pull/271 is otherwise sound, but forcing everyone to incur a cost (for no benefit) just to meet the needs of people who need fine-grain custom memory allocation is undesirable.

@AE1020 proposed a model that would fix the limitations of PR https://github.com/RoaringBitmap/CRoaring/pull/271 C by allowing custom memory allocators only for C++ builds, and only on demand (at compile-time). Thus there would be macro checks (for the C++ language), and then we would enable 'fat' containers when

    #ifdef ROARING_TUNNEL_ALLOCATORS
        #if !defined(__cplusplus)
             #error "ROARING_TUNNEL_ALLOCATORS requires building as C++"
        #endif
        struct augmented_ptr { ...

We have a prototypical code sample...
```C
#include <stdio.h>
#include <stdlib.h>

typedef struct { const char *container_stuff; } container_t;
typedef void* (allocator_t)(size_t);

#if !defined(__cplusplus)
    typedef container_t* augmented_ptr;
    
    #define ALLOCATOR_OF(augmented) malloc
    
    #define MAKE_AUGMENTED(container,allocator) container
#else
    struct augmented_ptr {
        container_t* c;
        allocator_t* a;

        augmented_ptr (container_t *cc, allocator_t *aa)
            : c (cc), a (aa)
            {}

        container_t* operator->() { return c; }
    };

    #define ALLOCATOR_OF(augmented) (*(augmented).a)

    #define MAKE_AUGMENTED(container,allocator) \
        augmented_ptr{(container), (allocator)}
#endif

void aware_receiver(augmented_ptr c) {
    void *data = ALLOCATOR_OF(c)(sizeof(int));
    // whatever...
}
    
void oblivious_function(augmented_ptr c) {
    printf("container stuff is: %s\n", c->container_stuff);
    aware_receiver(c);               // ^-- normal use of ->
}

augmented_ptr aware_generator(allocator_t *alloc, const char *stuff) {
    container_t *c = (container_t*)(*alloc)(sizeof(container_t));
    c->container_stuff = stuff;
    return MAKE_AUGMENTED(c, alloc);
}

void* myalloc(size_t size) {
    printf("Allocation requested for %ld bytes\n", size);
    return malloc(size);
}

int main()
{
  #if !defined(__cplusplus)
    allocator_t *a = &malloc;
  #else
    allocator_t *a = &myalloc;
  #endif

    augmented_ptr c = aware_generator(a, "some stuff");
    oblivious_function(c);
}
```

Pull requests are invited.

**Comment by Oppen** [comment]
Considering `malloc` can incur in a syscall I think it's not that bad to pay an extra regular function call in comparison, and that would help C users get this finer grained control too.

**Comment by Oppen** [comment]
Regardless, I'm not sure why a similar build-time solution can't be made in C with macros.

**Comment by lemire** [comment]
@Oppen There is no disagreement on the usefulness of the functionality. My overriding concerns here are code maintenance and performance. If we can achieve this functionality without performance penalty or without risking code maintenance issue, it is clear net win... 

In fact, I'd say that code maintenance is my primary overriding concern. We'd like a clean design that is easy to document, easy to test and so forth. This is not to say that the proposed design could not meet this bar, but the computation is somewhat different when the library is used for diverse purposes.
