### ISSUE TITLE
Double free when using roaring_bitmap_overwrite

### ISSUE THREAD

**Issue by Ezibenroc** [RoaringBitmap/CRoaring#288]
I tried to upgrade to CRoaring v0.3.0 in pyroaring and stumbled on a segmentation fault when running the tests. I tracked down the error to `roaring_bitmap_overwrite` function.

Here is a minimum example in C, using the amalgamated source (name it `mwe.c`):
```c
#include <stdio.h>
#include "roaring.c"

int main() {
  roaring_bitmap_t *r1 = roaring_bitmap_create();
  roaring_bitmap_t *r2 = roaring_bitmap_create();
  roaring_bitmap_add(r1, 42);

  roaring_bitmap_overwrite(r1, r2);

  roaring_bitmap_free(r1);
  roaring_bitmap_free(r2);
  return 0;
}
```
Compile and run with `cc -O3 -std=c11  -o mwe mwe.c && ./mwe`
It prints `free(): double free detected in tcache 2`

Interestingly, the error does not happen with `-O0` optimization flag, only `-O1` and higher. It does not happen with CRoaring v0.2.66.

**Comment by lemire** [comment]
I'll have a look today. I am not aware of any changes in this function. I will have to investigate.

**Comment by lemire** [comment]
The issue has been verified. This is weird because I don't remember any change with respect to this code.

**Comment by Ezibenroc** [comment]
Version v0.2.66 was made one year ago, it seems that some commits have been made on this function since (e.g. 948f8af9).

**Comment by lemire** [comment]
@Ezibenroc Yes. The bug is painfully obvious.

**Comment by lemire** [comment]
Patch coming up.

**Comment by lemire** [comment]
Look at the diff at https://github.com/RoaringBitmap/CRoaring/pull/289

**Comment by Ezibenroc** [comment]
Ah yes, indeed. I confirm this fixed the test on pyroaring side.
