### ISSUE TITLE
incorrect Roaring constructed from a COW-Enabled Roaring

### ISSUE THREAD

**Issue by longqimin** [RoaringBitmap/CRoaring#316]
i tried to build a COW-enabled Roaring, and then construct other Roarings from it. But the new constructed Roaring seems incorrect.

the problem can be repoduced as following:
```
void test_ctor_from_cow_cpp() {
    Roaring r1;
    r1.setCopyOnWrite(true);
    r1.addRange(1, 100);

    Roaring r2;
    r2 |= r1;
    auto r3 = r2;
    assert_true(r2.isSubset(r3));
}
```
and yields the error msg:
```
CRoaring/include/roaring/containers/containers.h:725: container_is_subset: Assertion `false' failed.
```

i found the error can be walk around by set COW on r2 (`r2.setCopyOnWrite(true);`).

is this a bug or misuse ？

ps. [dest->codetypes/contianers may mismatch in ra_overwrite()](https://github.com/RoaringBitmap/CRoaring/blob/master/src/roaring_array.c#L144)

**Comment by lemire** [comment]
At a glance, this seems like a bug. I will investigate.

**Comment by lemire** [comment]
Fix upcoming.
