### ISSUE TITLE
Efficient intersection of one bitmap with many

### ISSUE THREAD

**Issue by ELind77** [RoaringBitmap/CRoaring#318]
Hi all,

I'd like some advice on the most efficient way to query many bitmaps with a single bitmap.  Specifically, I have a query bitmap and a large set of bitmaps (~1 million) and I'd like to know which elements of the large set share at least one member with the query set (doesn't even need to be a full intersection).  If the best way to do this is to just write a loop then that's fine, but I thought I'd ask to see if there is some kind of optimized operation that can be done with one to many.  

-- Eric

**Comment by lemire** [comment]
> I'd like to know which elements of the large set share at least one member with the query set (doesn't even need to be a full intersection)

We have a function for this purpose:

```C++
/**
 * Check whether two bitmaps intersect.
 */
bool roaring_bitmap_intersect(const roaring_bitmap_t *r1,
                              const roaring_bitmap_t *r2);
```

It should be very fast.

Now, of course, there are cleverer ways to solve your problem for sure, but in the abstract, it is hard to tell.

I recommend implementing the loop with `roaring_bitmap_intersect` and see how well it does.

Always, always start with benchmarking if efficiency matters.

**Comment by Oppen** [comment]
@ELind77 did @lemire's answer satisfy you? Can we close the issue?

**Comment by ELind77** [comment]
Yes. Thank you!
