### ISSUE TITLE
Could you add a dist package for release?

### ISSUE THREAD

**Issue by QwertyJack** [RoaringBitmap/CRoaring#339]
Thanks for you great work!

The source code package is too big (100MB compressed and 300MB decompressed).
It would be nice to deliver a thin package.
Maybe just removing the `benchmark` dir would do the trick?

**Comment by QwertyJack** [comment]
Sorry my bad. I finally manage to see the Amalgamation section.
Could you back port this cute, amalgamated package to previous release?

**Comment by lemire** [comment]
@QwertyJack Is there any reason for not using version 0.4?

https://github.com/RoaringBitmap/CRoaring/releases/download/v0.4.0/roaring.zip

**Comment by lemire** [comment]
I would prefer to avoid pointing you at old releases.

**Comment by QwertyJack** [comment]
> I would prefer to avoid pointing you at old releases.
You are right.

Btw, appreciate if packing in `.tar.gz` instead of `.zip`, because `unzip` is not always there as for a common Linux box.
