### ISSUE TITLE
Documentation: roaring_bitmap_to_uint32_array -- output is ordered

### ISSUE THREAD

**Issue by dtenny** [RoaringBitmap/CRoaring#341]
Just following through with an issue for tracking.  I asked in the google group about whether `roaring_bitmap_to_uint32_array` could be relied upon to be ordered, Daniel said yes.  Documentation for the function should be updated.  (It's important because it let's people avoid the need fo sorting the output).

**Comment by dtenny** [comment]
Similar documentation may be useful for `roaring_bitmap_range_uint32_array`.

**Comment by lemire** [comment]
@dtenny I did update the doc/comments way back. Could you review the current status (main branch) and possibly close this issue if you are satisfied?

**Comment by dtenny** [comment]
> Convert the bitmap to a sorted array, output in `ans`.

Roger that, closing
