### ISSUE TITLE
Documentation: return value semantics of roaring_bitmap_overwrite

### ISSUE THREAD

**Issue by dtenny** [RoaringBitmap/CRoaring#342]
1. This would be improved by documenting the return semantics, true if the operation succeeded, false if the overwrite failed due to allocation failures.
2. It would be good to define the semantics w.r.t. the destination bitmap when false is returned. I _think_ that you've coded this so that the bitmap structure is internally consistent, so that it should be usable for future operations (memory permitting), but that its logical element content and resulting count is undefined.  That is how I've documented it for my users, please let me know if that's incorrect.

**Comment by lemire** [comment]
> the return semantics, true if the operation succeeded, false if the overwrite failed due to allocation failures.

Correct.

> It would be good to define the semantics w.r.t. the destination bitmap when false is returned. I think that you've coded this so that the bitmap structure is internally consistent, so that it should be usable for future operations (memory permitting), but that its logical element content and resulting count is undefined. That is how I've documented it for my users, please let me know if that's incorrect.

If false, then the destination should be the empty bitmap. So the content that was there should have been cleared. 

Would you propose a pull request ?
