### ISSUE TITLE
any faster way to check if exists difference (andnot) between two bitmaps

### ISSUE THREAD

**Issue by longqimin** [RoaringBitmap/CRoaring#355]
i have a function to check if `a` contains any element which not contained in `b`:

```
    auto check_andnot(const Roaring& a, const Roaring& b) -> bool {
        return a.andnot_cardinality(b) !=0;
    }
```

but it's a waste to calculate the accurate `andnot_cardinality`。 is there a faster way to achieve this?  thanks

**Comment by lemire** [comment]
We have `roaring_bitmap_contains`. It will return false if one bitmap is not contained in the other.

**Comment by longqimin** [comment]
> We have `roaring_bitmap_contains`. It will return false if one bitmap is not contained in the other.

i just found this: `bool roaring_bitmap_contains(const roaring_bitmap_t *r, uint32_t val);`, it checks single-value only

**Comment by lemire** [comment]
I am sorry, you are 100% correct.

**Comment by lemire** [comment]
We have `roaring_bitmap_intersect`, but we do not have in C a fast function that matches what you desire. 

Pull request invited !

**Comment by lemire** [comment]
It should be relatively easily implemented. It is just like `andnot_cardinality` but it exits as soon as the cardinality is found to be non-zero.

**Comment by lemire** [comment]
That would be fantastic.

**Comment by longqimin** [comment]
@lemire https://github.com/RoaringBitmap/CRoaring/pull/356

**Comment by longqimin** [comment]
resolved. use `roaring_bitmap_is_subset()`, which exported by Roaring as Roaring::is_subset()
