### ISSUE TITLE
Small number of non "roaring"-prefixed items exported

### ISSUE THREAD

**Issue by Dr-Emann** [RoaringBitmap/CRoaring#359]
There are a small number of items exposed which do not start with "roaring". I think it would be useful to consider adding/changing a few names of things currently exported to always have everything expected to be exported prefixed with roaring.

The following items are the only items we export from the api headers that don't have the same naming convention as all others, looking at the [official API header files](https://github.com/RoaringBitmap/CRoaring/blob/4f8dbdb0cc884626b20ef0cc9e891f701fe157cf/amalgamation.sh#L31-L35):

* [`MAX_CONTAINERS`](https://github.com/RoaringBitmap/CRoaring/blob/4f8dbdb0cc884626b20ef0cc9e891f701fe157cf/include/roaring/roaring_types.h#L38) This is a very common-sounding define, and it feels like we _really_ should prefix this. Should this even be publicly exposed?
* [`SERIALIZATION_ARRAY_UINT32`](https://github.com/RoaringBitmap/CRoaring/blob/4f8dbdb0cc884626b20ef0cc9e891f701fe157cf/include/roaring/roaring_types.h#L40) & [`SERIALIZATION_CONTAINER`](https://github.com/RoaringBitmap/CRoaring/blob/4f8dbdb0cc884626b20ef0cc9e891f701fe157cf/include/roaring/roaring_types.h#L41). Should we be exposing these in the public api?
* Several items from [`memory.h`](https://github.com/RoaringBitmap/CRoaring/blob/4f8dbdb0cc884626b20ef0cc9e891f701fe157cf/include/roaring/memory.h). Could these be renamed to start with `roaring_` instead?:
    * `p_roaring_malloc`
    * `p_roaring_realloc`
    * `p_roaring_calloc`
    * `p_roaring_free`
    * `p_roaring_aligned_malloc`
    * `p_roaring_aligned_free`
    * `init_roaring_memory_hook`

**Comment by lemire** [comment]
I am issuing a PR. You have a good point.

> Could these be renamed to start with roaring_ instead?

The essential goal is to prevent name clashes. After that we get into bike shedding and I reject bike shedding.

**Comment by Dr-Emann** [comment]
The other reason to keep everything with a common `roaring_*` prefix is to make ffi generation easier. e.g. the croaring-rs rust bindings [currently](https://github.com/saulius/croaring-rs/blob/d5e3e6187ad550bba482aa8e58d518ecffe12547/croaring-sys/build.rs#L21-L24) uses that prefix to only generate bindings for croaring functions/types/constants. It's likely it could get away with `.*roaring.*`, and not pick up anything else, but it feels a tiny bit dirty.

The items from `memory.h` haven't yet been part of a release yet, if that also helps the case for changing them?
