### ISSUE TITLE
summary of roaring bitmap

### ISSUE THREAD

**Issue by brentp** [RoaringBitmap/CRoaring#36]
Not sure if this is too high-level for this library, but
maybe something like:
```
typedef struct summary_s {
    uint32_t n_arrays 
    uint32_t n_rle
    uint32_t n_bitmap
    // and n_values_arrays, n_values_rle, n_values_bitmap ?
} summary_t

summary_t *roaring_bitmap_summary(roaring_bitmat_t *r)
```

from there, it's simpler to calculate sparsity and simple functions to show the different use of each container type.

**Comment by lemire** [comment]
Sure. This is easy. Do you want to define the variables of interest?

**Comment by brentp** [comment]
I think the main things of interested would be total % of containers of each type and % of values in each type of container.

also, total calculated memory-use (then easy to derive bits / int stored)

maybe also a measure of sparsity, e.g. how many empty (non-existent) containers. and/or entropy.

**Comment by lemire** [comment]
Implemented as per this commit 

https://github.com/RoaringBitmap/CRoaring/commit/7fa04a660296e58a1baf7ba2714d1cba27999f16


Closing. Reopen if you disagree.
