### ISSUE TITLE
#define _GNU_SOURCE is causing some issues with other libraries

### ISSUE THREAD

**Issue by GuillaumeHolley** [RoaringBitmap/CRoaring#365]
Hi,

I am using CRoaring in one of my projects which also uses some other libraries. Recently, I got a bug report from an x86 Mac user compiling the project with AppleClang. Specifically, one of the libraries contains the following line in one of its header:
```
#if ((_POSIX_C_SOURCE >= 200112L || _XOPEN_SOURCE >= 600 || defined(__APPLE__)) && ! _GNU_SOURCE) || defined(__MUSL__)
```
and the compiler was issuing an `error: expected value in expression` error while pointing at `_GNU_SOURCE`. Testing for `! GNU_SOURCE` seems to be valid according to the [following page](https://linux.die.net/man/3/strerror_r). I couldn't understand for the life of me what was the issue, why it didn't have a value, given that I never touched `_GNU_SOURCE` so I temporarily solved the issue by replacing `_GNU_SOURCE` in the library with `(_GNU_SOURCE+0)`.
I now realize that CRoaring contains the [following lines](https://github.com/RoaringBitmap/CRoaring/blob/889df7b45474fb94c5708f79cdf08ba1b429b32b/include/roaring/portability.h#L10):
```
#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif // _GNU_SOURCE
```
So `_GNU_SOURCE` is effectively defined but without a value. I think setting it to 1 would solve the issue and it wouldn't affect CRoaring at all:
```
#ifndef _GNU_SOURCE
#define _GNU_SOURCE 1
#endif // _GNU_SOURCE
```

Thanks,
Guillaume

PS: I do not have this issue when I compile on Linux with GCC.

**Comment by lemire** [comment]
Sure. Would you create a pull request ?

**Comment by GuillaumeHolley** [comment]
Yes, I'll get on it.
