### ISSUE TITLE
how to get a roaring object's footprinter?

### ISSUE THREAD

**Issue by hurricane1026** [RoaringBitmap/CRoaring#367]

**Comment by hurricane1026** [comment]
there is no any function for getting memory footprinter in CRoaring.
I found this in C API.
https://github.com/RoaringBitmap/CRoaring/blob/74bac27f0ed412bd4fca4b06d51f7c9e05e563ef/include/roaring/roaring.h#L683
but in implementation, all nbytes is for serialization.
If I want to cache some roaring_bitmap_t in memory, it need the memory footprinter of it.

**Comment by lemire** [comment]
From our README:


```C
// we can write a bitmap to a pointer and recover it later
    uint32_t expectedsize = roaring_bitmap_portable_size_in_bytes(r1);
    char *serializedbytes = malloc(expectedsize);
    roaring_bitmap_portable_serialize(r1, serializedbytes);
```

**Comment by hurricane1026** [comment]
hi, @lemire I am afraid of you hadn't understand me, 
the roaring_bitmap_portable_size_in_bytes function get the size of the serialize buffer's size, but I want to get the bitmap size in the memory, just like a sizeof operator for roaring_bitmap_t struct.

**Comment by lemire** [comment]
You may find the following reference useful: [Measuring memory usage: virtual versus real memory](https://lemire.me/blog/2021/07/29/measuring-memory-usage-virtual-versus-real-memory/).

**Comment by lemire** [comment]
This issue is now closed. We recommend that users who are concerned with precise memory usage measurements track the physical pages assigned to their process by the operating system. Doing so requires OS-specific code.
