### ISSUE TITLE
Roaring64Map::flip excludes all uint32 max values

### ISSUE THREAD

**Issue by SLieve** [RoaringBitmap/CRoaring#372]
`Roaring64Map::flip` calls `Roaring::flip` like this:

```
            roarings[start_high].flip((std::numeric_limits<uint32_t>::min)(),
                                      (std::numeric_limits<uint32_t>::max)());
```

Since `Roaring::flip` operates on a right-open interval, this results in the max value of each 32-bit roaring to be unaffected.

To reproduce:
```
roaring::Roaring64Map r;
r.add(0ul);
r.add(1ul << 32);
r.flip(0, 1ul << 32);
assert(r.contains((1ul << 32) - 2)); // passes
assert(r.contains((1ul << 32) - 1)); // fails
```

It seems like an easy fix: use uint32 max + 1 instead of uint32 max for the upper bound, as `Roaring::flip` accepts 64-bit values just for this purpose.

**Comment by lemire** [comment]
Would you issue a pull request?

Please add both a test and your fix.
