### ISSUE TITLE
Memory allocation/deallocation in caller/callee

### ISSUE THREAD

**Issue by Ezibenroc** [RoaringBitmap/CRoaring#39]
There is this function in `roaring.h`:

```c
/**
 * Convert the bitmap to an array. Array is allocated and caller is responsible
 * for eventually freeing it.
 */
uint32_t *roaring_bitmap_to_uint32_array(const roaring_bitmap_t *ra,
                                         uint32_t *cardinality);
```
Currently, the callee allocates the memory, therefore, it should be responsible of freeing it. So I think the library should provide the corresponding function:
```c
void free_array(uint32_t *array);
```
Alternatively, the caller could be responsible of allocating the array (but it would require a call to `roaring_bitmap_get_cardinality` before):
```c
void roaring_bitmap_to_uint32_array(const roaring_bitmap_t *ra, uint32_t * array);
```

The issue is the same for `roaring_bitmap_serialize`.

**Comment by lemire** [comment]
Agreed. Fixed as per https://github.com/RoaringBitmap/CRoaring/commit/3ec88d72725b4d88a1ff812a71db8079665e514e

Reopen if you disagree.

**Comment by Ezibenroc** [comment]
There is apparently a bug, but I cannot find its cause.

When I run the test `toplevel_unit`, it does not terminate. However, there is no significant CPU load, so it is not an infinite loop.
This still happens if I remove all the sub-tests except  `test_portable_serialize` and `test_serialize`. But if I remove one of these two tests, then the process terminates normally.
I can also remove a great part of these two tests and still have this bug (I can paste here the minimal example, if needed).

I did not test this yet on an other machine.

Valgrind says there are invalid writes in `bitset_extract_setbits_avx2` (used by `roaring_bitmap_to_uint32_array`), maybe it is related.

**Comment by lemire** [comment]
Yes, it passes tests for me but I did not check valgrind... let me see...

**Comment by lemire** [comment]
@Ezibenroc 

Should be good now with this commit...
https://github.com/RoaringBitmap/CRoaring/commit/f9a5b494b0eafe7e1c1a1325fea729cf5b21a388
