### ISSUE TITLE
Use more specific macros and functions to decide whether to use vectorized methods.

### ISSUE THREAD

**Issue by CharlesChen888** [RoaringBitmap/CRoaring#391]
I'm using CRoaring in my project and I want to use the vectorized bitwise computing methods for better performance. However, my dev machine (and maybe some of our online servers) does not support AVX2. 

I looked into the code and I found that some of those vectorized methods don't need AVX2 instructions. For example, in `intersect_vector16` there are `_mm_lddqu_si128`, `_mm_load_si128`, `_mm_storeu_si128`, `_mm_shuffle_epi8`, which needs only SSE2 and SSE3 support, and my machine supports them. But I can only use this function (through higher level API) when I enabled AVX2 when compiling, which also enables functions that use `_mm256_and_si256`, and my machine cannot run it.

How about using more specific macros like `__SSE3__`, `__SSE2__` and add more funcitons like `croaring_sse3` to specify what support a function actually needs, instead of just using `__AVX2__` to switch on and off all optimizations? This will enable those old machines to use at least some of the optimized funtions.

**Comment by CharlesChen888** [comment]
Alright I've just found that this is actually an old issue #92

**Comment by lemire** [comment]
A pull request is invited.

Note that AVX2 is effectively ubiquitous on x64 hardware at this time. I don't think Intel and AMD sell commodity processors at this point in time without AVX2.

It would be more interesting to me to include support for AVX-512, now that icelake servers are everywhere (AWS, and so forth) and with Zen 4 providing great AVX-512 support.

**Comment by CharlesChen888** [comment]
Yes, AVX512 should be included, both old and new machine support can be done together.

**Comment by lemire** [comment]
I agree.
