### ISSUE TITLE
Trouble building 0.7.1 amalgamation on Windows

### ISSUE THREAD

**Issue by SamHames** [RoaringBitmap/CRoaring#394]
Hi there, I'm doing a [bit of maintenance work](https://github.com/Ezibenroc/PyRoaringBitMap/issues/78) on the Python package for pyroaring and have run into an issue with building the 0.7.1 release amalgamation on Windows. I originally ran into this [on a CI build on windows](https://github.com/SamHames/PyRoaringBitMap/actions/runs/3343247445/jobs/5536267822), but can reproduce the same error with the demo.c example program. I can also confirm that the [0.6.0 release amalgamation works fine](https://github.com/SamHames/PyRoaringBitMap/actions/runs/3390503195/jobs/5634726059). 

Error details from CI (same errors seen when trying to compile the demo.c program with cl):

```
"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.33.31629\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -ID:\a\PyRoaringBitMap\PyRoaringBitMap\.tox\test\include -Ic:\hostedtoolcache\windows\python\3.7.9\x64\include -Ic:\hostedtoolcache\windows\python\3.7.9\x64\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.33.31629\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.33.31629\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" /EHsc /Tcpyroaring\roaring.c /Fobuild\temp.win-amd64-cpython-37\Release\pyroaring\roaring.obj
roaring.c
pyroaring\roaring.c(178): warning C4013: '__asm__' undefined; assuming extern returning int
pyroaring\roaring.c(178): error C2143: syntax error: missing ')' before ':'
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.33.31629\include\stdatomic.h(15): fatal error C1189: #error:  <stdatomic.h> is not yet supported when compiling as C, but this is planned for a future release.
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
[end of output]
```

I took a look at the amalgamation and the source (but this is a bit outside my area so could be wrong) that the issue is an ordering issue with how `portability.h` and `isadetection.h` are included in the amalgamation with the recent changes for clangcl in #375 . In the source distribution `isadetection.h` is included in `portability.h`, and now appears to depend on the early defines in `portability.h`, but in the amalgamation `isadetection.h` is inserted before `portability.h`.

Please let me know if there's anything else you need from me to help.

**Comment by lemire** [comment]
I will examine the issue right away.
