### ISSUE TITLE
Make the headers C++ compatible

### ISSUE THREAD

**Issue by kishorenc** [RoaringBitmap/CRoaring#4]
Thank you for this library. I am trying to use CRoaring in a C++ project but I run into a compilation issue because of a line like this:

https://github.com/RoaringBitmap/CRoaring/blob/3572bc80dfd5388dcc317566cf43bf9814c245ee/include/containers/containers.h#L43

In C++, the void pointer has to be cast to match the type of the calling function's argument. It would be even better if the header files are free of actual implementation, as having them it in the `.c` files is both recommended and speed up compilation greatly.

**Comment by owenkaser** [comment]
As of a few days ago, the library was not ready for general use, even as
alpha software.  Others can perhaps tell you when it might be ready for
experimentation, but I don't think it is particularly soon.

The routines in question are supposed to be inline, although the compiler
is currently not choosing to inline them.   This is why they are in a
header file. Your point about typecasting of void pointers is interesting,
as I had originally done a lot of such typecasting, but then realized that
it was unnecessary in C.

**Comment by kishorenc** [comment]
Thanks, understood.

Yes, the typecasting is not necessary in C and is completely fine being on a `.c` file. But, when it's in a header file, you can't include those headers in a CPP file because that's not valid C++.

**Comment by lemire** [comment]
@kishorenc 

Thanks.

As Owen pointed out, the library is not yet ready even for alpha use... 

Inline implementations are provided in header files to allow function inlining. Since a function call costs something like 30 cycles it is an important optimization. This is supported both in C and C++.

It makes sense to make sure the code is usable from C++.

Let us leave this issue open.

**Comment by lemire** [comment]
We are going to leave this issue open. To be resolved.

**Comment by lemire** [comment]
Solved https://github.com/RoaringBitmap/CRoaring/commit/53cf248caeab4d66d6689426b5b38f5c7743f936
