### ISSUE TITLE
toUint64Array into a std::vector

### ISSUE THREAD

**Issue by maxdemarzi** [RoaringBitmap/CRoaring#416]
Trying to go from a Roaring64Map to a std::vector, this doesn't work:

          std::vector<uint64_t> ids;
          ids.reserve(map.cardinality());
          uint64_t* arr = ids.data();
          map.toUint64Array(arr);

But if I create a new array pointer then it works:

          uint64_t *arr1 = new uint64_t[map.cardinality()];
          map.toUint64Array(arr1);
          std::vector<uint64_t> ids(arr1, arr1 + map.cardinality());

Or if I use two vectors with assign:

          std::vector<uint64_t> ids;
          ids.reserve(map.cardinality());
          std::vector<uint64_t> array;
          array.reserve(map.cardinality());
          map.toUint64Array(array.data());
          ids.assign(array.data(), array.data() + map.cardinality());

What's the right way to do this? 

Or would it make sense to add a Roaring64Map::toVector method?

**Comment by lemire** [comment]
As you know, this code is not safe as per the standard...

```C++
      std::vector<uint64_t> ids;
      ids.reserve(map.cardinality());
      uint64_t* arr = ids.data();
      map.toUint64Array(arr);
```

You need `resize()` (as you know):


```C++
      std::vector<uint64_t> ids;
      ids.resize(map.cardinality());
      uint64_t* arr = ids.data();
      map.toUint64Array(arr);
```


I expect that It is going to be efficient and safe with the resize()/data()/toUint64Array routine describe above. You may argue that `resize()` is bound to clear the content first... but if it is new memory, then it must do so anyhow (data gets into your process after being cleaned, for security reasons), and if not, then it is a mere memset, which is going to be efficient... meaning that the cost is small compared to the cost of `toUint64Array`, so small that it is effectively zero, as long as `map.cardinality()` is not too large (compared to the CPU L3 cache). Of course, you can benchmark. If you find yourself in a scenario where initializing the memory is too expensive, you are probably going to want to roll your own data structures anyhow... (not `std::vector`).

**Comment by maxdemarzi** [comment]
Thank you!
