### ISSUE TITLE
missing from C example in README

### ISSUE THREAD

**Issue by rsharris** [RoaringBitmap/CRoaring#42]
In the snippet under "we can also go in reverse", rf1 is never created or declared.  I think you intended this statement before free(arr1):
   roaring_bitmap_t *r1f = roaring_bitmap_of_ptr(card1, arr1);
and then there should also be a call to free rf1
   roaring_bitmap_free(r1f);

**Comment by lemire** [comment]
Yes. Thanks. Fixed.
