### ISSUE TITLE
Set minimum permissions to workflows

### ISSUE THREAD

**Issue by gabibguti** [RoaringBitmap/CRoaring#447]
Setting minimum permissions to workflows is important to keep your repository safe against supply-chain attacks. GitHub gives each workflow a GITHUB_TOKEN to execute the actions, and this GITHUB_TOKEN has higher permissions than necessary by default. By setting only the necessary permissions, we are more protected against some supply-chain attacks.

Looks like a good number of workflows use only `actions/checkout` which needs only `contents: read` permission to read the repository code. Other workflows would need a closer look to understand the necessary permissions. If you agree with these changes, I can do a better analysis and open a PR!

Restricting workflow permissions is recommended by [GitHub itself](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) and other security tools, such as [Scorecards](https://github.com/ossf/scorecard) and [StepSecurity](https://github.com/step-security).

##### Additional context
I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by lemire** [comment]
PR invited Gabriela.
