### ISSUE TITLE
compile error missing croaring_has_avx512

### ISSUE THREAD

**Issue by feng-y** [RoaringBitmap/CRoaring#461]
croaring/src/isadetection.c:245:40: error: implicit declaration of function 'croaring_has_avx512' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    support = ROARING_SUPPORTS_AVX2 | (croaring_has_avx512() ? ROARING_SUPPORTS_AVX512 : 0);

compile version: clang-11.1

**Comment by lemire** [comment]
Give me a minute.
