### ISSUE TITLE
Can't compile older gcc (<8.1)

### ISSUE THREAD

**Issue by toge** [RoaringBitmap/CRoaring#484]
In 1.1.4, I get a compile error with old gcc (< 8.1).
A simple bug in portability.h seems to be the cause.

By [this commit](https://github.com/RoaringBitmap/CRoaring/commit/264b18882fa7124f2abae959697cdd03dd6584ec), `CROARING_CLANG_VISUAL_STUDIO` is always defined.

```cpp
#ifndef CROARING_VISUAL_STUDIO
#define CROARING_VISUAL_STUDIO 0
#endif
#ifndef CROARING_CLANG_VISUAL_STUDIO
#define CROARING_CLANG_VISUAL_STUDIO 0
#endif
#ifndef CROARING_REGULAR_VISUAL_STUDIO
#define CROARING_REGULAR_VISUAL_STUDIO 0
#endif
```

But portability.h only checks if `CROARING_CLANG_VISUAL_STUDIO` is defined.

https://github.com/RoaringBitmap/CRoaring/blob/master/include/roaring/portability.h#L110

```cpp
#ifdef CROARING_CLANG_VISUAL_STUDIO

/**
 * You are not supposed, normally, to include these
 * headers directly. Instead you should either include intrin.h
 * or x86intrin.h. However, when compiling with clang
 * under Windows (i.e., when _MSC_VER is set), these headers
 * only get included *if* the corresponding features are detected
 * from macros:
```

I think this should be `#if CROARING_CLANG_VISUAL_STUDIO`.
Is this correct?

**Comment by lemire** [comment]
Yes. It looks like you are correct. We will patch this issue.
