### ISSUE TITLE
Support `roaring_bitmap_add_bulk` in C++ interface

### ISSUE THREAD

**Issue by mapleFU** [RoaringBitmap/CRoaring#491]
Currently, I want to insert some numbers in C++ code, I find there're three interfaces:

1. `roaring_bitmap_add`
2. `roaring_bitmap_add_many`
3. `roaring_bitmap_add_buck`

Now I found there are not `roaring_bitmap_add_buck` case in C++. Should we support that? Or this interface is just deprecated?

**Comment by lemire** [comment]
The C++ wrapper provides some of the functionality of the library but not all of it. If you need the roaring_bitmap_add_bulk functionality from C++, then I recommend you provide a pull request. The pull request should include tests and documentation.
