### ISSUE TITLE
Linking errors on MacOSX

### ISSUE THREAD

**Issue by petersteneteg** [RoaringBitmap/CRoaring#501]
When building a shared lib on macosx the rpath needs to be used for the linking to work
For odd reasons this was disabled here
https://github.com/RoaringBitmap/CRoaring/commit/afa990bf20faf3173568e3532c761abcd4ba08a0

Enabling it again makes everything work as expected. 

Without it the dynamic linker will not find the library at runtime

**Comment by lemire** [comment]
Thanks for reporting the issue. Fixed by the latest PR. It will be part of the next release.
