### ISSUE TITLE
CRoaring does not support the Intel compiler

### ISSUE THREAD

**Issue by rohanaggarwal7997** [RoaringBitmap/CRoaring#506]
Hi these macros do not work with ICC leading to the compiler companing that unknown pragma and not generating the vector code. Any tips ?

#define CROARING_TARGET_AVX2 #pragma push_options #pragma intel optimization_par     ameter target_arch=AVX2,BMI,PCLMUL,LZCNT,POPCNT
#define CROARING_TARGET_AVX512 #pragma push_options #pragma intel optimization_p     arameter target_arch=avx2,bmi,bmi2,pclmul,lzcnt,popcnt,avx512f,avx512dq,avx512bw     ,avx512vbmi2,avx512bitalg,avx512vpopcntdq 
#define CROARING_UNTARGET_AVX2 #pragma pop_options 
#define CROARING_UNTARGET_AVX512 #pragma pop_options

I get the following warning

For array_util.c(2142): warning #1879: unimplemented pragma ignored CROARING_TARGET_AVX512

**Comment by lemire** [comment]
The classical Intel compiler ICC is deprecated by Intel. Please don't use it.

Building with the new Intel compiler (ICX) is doable, though it is not currently possible to compile Google Benchmarks by default and that's a problem because we rely on Google Benchmarks: I added a commit that removes Google Benchmarks as a dependency by default.

You can now build CRoaring with the (new) Intel compiler like so...
```
CC=putyourdir/intel/oneapi/compiler/2023.2.1/linux/bin/icx CXX=putyourdir/intel/oneapi/compiler/2023.2.1/linux/bin/icpx cmake -B buildintel && cmake --build buildintel -j
```

Unfortunately, the resulting code might not be correct. It currently does not pass our unit tests.

It is unclear to me whether this is an indication of a bug in our code, or some problem with ICX. Given that ICX cannot seems to choke on Google Benchmarks, I suspect that it has some problems.

Pull requests are invited if you want to investigate the issue and help us support Intel compilers.

**Comment by lemire** [comment]
Note:

```
Intel® C++ Compiler Classic (icc) is deprecated and will be removed in a oneAPI release in the second half of 2023. Intel recommends that customers transition now to using the LLVM-based Intel® oneAPI DPC++/C++ Compiler (icx) for continued Windows* and Linux* support, new language support, new language features, and optimizations.
```
https://community.intel.com/t5/Intel-oneAPI-IoT-Toolkit/DEPRECATION-NOTICE-Intel-C-Compiler-Classic/m-p/1412267#M66

**Comment by lemire** [comment]
Maybe Intel folks could help: @huihan365 @linlifan @geofflangdale  

What is the story with the Intel compilers at this time and what should our expectations be?

I have not investigated deeply. 

Note: We definitively would want to support the Intel compiler if possible.

**Comment by vesslanjin** [comment]
> Maybe Intel folks could help: @huihan365 @linlifan @geofflangdale
> 
> What is the story with the Intel compilers at this time and what should our expectations be?
> 
> I have not investigated deeply.
> 
> Note: We definitively would want to support the Intel compiler if possible.

have submited a ticket to compiler team. pls stay tune.

**Comment by rohanaggarwal7997** [comment]
@lemire I did the following


mkdir -p build
cd build
/scratch/rohaagga/cmake_install/bin/cmake -DCMAKE_C_COMPILER=/usr/local/packages/icc_remote/v2021.9/compiler/2023.1.0/linux/bin/intel64/icc -DCMAKE_CXX_COMPILER=/usr/local/packages/icc_remote/v2021.9/compiler/2023.1.0/linux/bin/intel64/icpc ..
/scratch/rohaagga/cmake_install/bin/cmake --build .

And then ran
/scratch/rohaagga/cmake_install/bin/ctest

[root@phoenix95642 build]# /scratch/rohaagga/cmake_install/bin/ctest
Test project /scratch/rohaagga/CRoaring/build
      Start  1: cpp_unit
1/18 Test  #1: cpp_unit .........................   Passed   32.62 sec
      Start  2: cpp_random_unit
2/18 Test  #2: cpp_random_unit ..................   Passed    0.69 sec
      Start  3: cpp_example1
3/18 Test  #3: cpp_example1 .....................   Passed    0.00 sec
      Start  4: cpp_example2
4/18 Test  #4: cpp_example2 .....................   Passed    0.00 sec
      Start  5: c_example1
5/18 Test  #5: c_example1 .......................   Passed    0.00 sec
      Start  6: cbitset_unit
6/18 Test  #6: cbitset_unit .....................   Passed    0.03 sec
      Start  7: array_container_unit
7/18 Test  #7: array_container_unit .............   Passed    5.53 sec
      Start  8: bitset_container_unit
8/18 Test  #8: bitset_container_unit ............   Passed    0.01 sec
      Start  9: mixed_container_unit
9/18 Test  #9: mixed_container_unit .............   Passed  115.78 sec
      Start 10: run_container_unit
10/18 Test #10: run_container_unit ...............   Passed    0.15 sec
      Start 11: toplevel_unit
11/18 Test #11: toplevel_unit ....................   Passed   15.14 sec
      Start 12: util_unit
12/18 Test #12: util_unit ........................   Passed    0.16 sec
      Start 13: format_portability_unit
13/18 Test #13: format_portability_unit ..........   Passed    0.00 sec
      Start 14: robust_deserialization_unit
14/18 Test #14: robust_deserialization_unit ......   Passed    0.00 sec
      Start 15: container_comparison_unit
15/18 Test #15: container_comparison_unit ........   Passed    0.02 sec
      Start 16: add_offset
16/18 Test #16: add_offset .......................   Passed    0.03 sec
      Start 17: threads_unit
17/18 Test #17: threads_unit .....................   Passed    0.00 sec
      Start 18: realdata_unit
18/18 Test #18: realdata_unit ....................   Passed   13.44 sec
 
100% tests passed, 0 tests failed out of 18

**Comment by lemire** [comment]
@rohanaggarwal7997 I am glad it works for you.

We are not going to support ICC since Intel is dropping support for it. Please update to ICX if you want support.

We will try our best to support the current Intel compiler (ICX).

**Comment by rohanaggarwal7997** [comment]
@lemire  I have removed the targets by doing the following

#if defined(__ICC)

#undef ALLOW_UNALIGNED
#define ALLOW_UNALIGNED

#undef CROARING_TARGET_AVX2
#define CROARING_TARGET_AVX2
#undef CROARING_UNTARGET_AVX2
#define CROARING_UNTARGET_AVX2
#undef CROARING_TARGET_AVX512
#define CROARING_TARGET_AVX512
#undef CROARING_UNTARGET_AVX512
#define CROARING_UNTARGET_AVX512

#endif

I get 
<img width="1192" alt="image001" src="https://github.com/RoaringBitmap/CRoaring/assets/24482442/110eb2c6-7992-4bfa-be31-fc2247d72d82">
AVX instructions dispatch because ICC compiles them regardless. I wanted to ask will this affect lzcnt,blsr and popcnt ?
I do not see usages of lzcnt and blsr in the code.

**Comment by lemire** [comment]
@rohanaggarwal7997 Please do not use ICC. We will not support ICC as it is deprecated. Upgrade to ICX.

Please follows Intel's advice:

> Intel® C++ Compiler Classic (icc) is deprecated and will be removed in a oneAPI release in the second half of 2023. Intel recommends that customers transition now to using the LLVM-based Intel® oneAPI DPC++/C++ Compiler (icx) for continued Windows* and Linux* support, new language support, new language features, and optimizations.


I am committed to supporting ICX from now on. I will not provide any support for ICC from now on.

This issue is closed.

**Comment by rohanaggarwal7997** [comment]
We cannot till next year. We have to use ICC till next year.

**Comment by lemire** [comment]
The library is open source and you are free to use it as you see fit. We will be happy to receive pull requests.

We will not work to provide ICC support. If you need ICC support, you need to take the full cost of the support.

This means that we do not provide any guarantees regarding efficiency.
