### ISSUE TITLE
Flagging supply-chain security issues 

### ISSUE THREAD

**Issue by gabibguti** [RoaringBitmap/CRoaring#521]
Hi @lemire! I just noticed you are also maintaining https://github.com/bits-and-blooms/bitset repository, to which I have been suggesting similar contributions. As in bits-and-blooms/bitset, I would like to know if you'd agree to add [Scorecard](https://github.com/ossf/scorecard) security tool to this repository, RoaringBitmap/CRoaring.

#### More about Scorecard and flagging supply-chain security issues

Flagging supply-chain security issues can help you, well, prevent supply-chain attacks. Supply-chain attacks aim for your development, build and release weaknesses. That's why, when we use minimum permissions for actions and reference actions by commit SHA even on test workflows, we help protecting the development process from malicious actions.

In this repository, we have already worked to flag and fix a few supply-chain security issues. To flag more issues like that we can use Scorecard security tool and receive alerts in GitHub's Security Dashboard. If you are willing to try out the tool in this repository, let me know, I can open a PR.

#### Additional Context

Hi again! I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by lemire** [comment]
Pull request invited.
