### ISSUE TITLE
Invalid sets and segfaults after add_offset

### ISSUE THREAD

**Issue by SamHames** [RoaringBitmap/CRoaring#538]
I ran into a [couple of issues with shift operations in  pyroaring](https://github.com/Ezibenroc/PyRoaringBitMap/issues/104), which might be a bug in croaring? Or we're holding it wrong :) 

The first issue seems to somehow be related to serialising/deserialising a bitmap after shifting, and results in very weird behaviour - the resulting bitmap seems to have the correct cardinality, but is definitely no longer a valid set.  I *think* the Python corresponds to the following C, based on the v2.1.0 amalgamated release.

```c
#include <stdio.h>
#include <stdlib.h>
#include "roaring.c"
int main() {

  roaring_bitmap_t *dense = roaring_bitmap_create();

  // Make a bitmap with enough entries to need a bitset container
  for (int k = 0; k < 4500; ++k) {
        roaring_bitmap_add(dense, 2 * k);
  }

  // Shift it to partly overlap with the next container.
  roaring_bitmap_t *dense_shift = roaring_bitmap_add_offset(dense, 64000);

  // Serialise and deserialise
  int buffer_size = roaring_bitmap_portable_size_in_bytes(dense_shift);

  char *arr = NULL;
  arr = malloc(buffer_size * sizeof(char));

  roaring_bitmap_portable_serialize(dense_shift, arr);

  roaring_bitmap_t *deserialized = roaring_bitmap_portable_deserialize(arr);

  // Iterate through the deserialised bitmap - This should be the same set as before
  // just shifted...
  roaring_uint32_iterator_t *iterator = roaring_create_iterator(deserialized);

  while (iterator->has_value)
  {
      printf("value = %d\n", (int) iterator->current_value);
      roaring_advance_uint32_iterator(iterator);
  }

  roaring_free_uint32_iterator(iterator);

  printf("cardinality = %d\n", (int) roaring_bitmap_get_cardinality(dense_shift));
  printf("cardinality = %d\n", (int) roaring_bitmap_get_cardinality(deserialized));

  roaring_bitmap_free(dense);
  roaring_bitmap_free(dense_shift);
  roaring_bitmap_free(deserialized);

}

```

For the second example the segfault happens in the call to `roaring_bitmap_equals`, but as far as I can tell only happens with copy_on_write on.

**Comment by lemire** [comment]
Please update to the latest version of CRoaring. It should fix the issue. Thanks for reporting it.

**Comment by lemire** [comment]
Yes. I have the fix. Will release soon.

**Comment by lemire** [comment]
Please update : https://github.com/RoaringBitmap/CRoaring/releases/tag/v2.1.2

**Comment by lemire** [comment]
I introduce a leak in the last release.

**Comment by lemire** [comment]
Ah. No. The leak is in @SamHames's code. Ok.

**Comment by lemire** [comment]
See https://github.com/RoaringBitmap/CRoaring/pull/541
