### ISSUE TITLE
Include update() function to take an array of values

### ISSUE THREAD

**Issue by Ezibenroc** [RoaringBitmap/CRoaring#54]
This issue comes from the one created by @brentp : https://github.com/Ezibenroc/PyRoaringBitMap/issues/13

There is no function in CRoaring to add several values to a bitmap. Currently, one has to either add these values one by one (very expensive if this is done in a wrapper, since function calls cost a lot), or create a new bitmap with them and compute the union (also a bit expensive since we have to do some allocations).

I guess that a trivial implementation (a simple for loop to add all the values) would already be an improvement for the wrappers.

**Comment by lemire** [comment]
What about adding a function with the following signature...

```
void roaring_bitmap_add_all(roaring_bitmap_t *r, size_t howmany, uint32_t * array);
```

For good measure, we could similarly add the following... 


```
void roaring_bitmap_remove_all(roaring_bitmap_t *r, size_t howmany, uint32_t * array);
```

(Just for symmetry.)

**Comment by lemire** [comment]
c.c. @brentp

**Comment by Ezibenroc** [comment]
Yes these functions would be great.

**Comment by fsaintjacques** [comment]
Would there be any values in creating a small struct that represents many values, e.g.

`typedef struct ra_indices { size_t n; uint32_t *indices } ra_indices_t;`? It seems this pattern is repeated in a lot of places.

**Comment by lemire** [comment]
@Ezibenroc  What do you think of @fsaintjacques's proposal?

**Comment by fsaintjacques** [comment]
The goal here is just to alleviate/minimize function signatures.

**Comment by Ezibenroc** [comment]
Yes this would be nice, as long as it is consistent in CRoaring.

**Comment by brentp** [comment]
I'm fine with either signature. I had to get around this in the cgo bindings as well:
https://github.com/RoaringBitmap/gocroaring/blob/master/gocroaring.go#L11
(and now I see I'm not freeing a bitmap there)

might be an interesting area of research to see how to optimize this. The benchmarks in gocroaring show it's faster (not suprisingly) to add sorted values--which for me will be a common use-case.
And one could also imagine accumulating sorted values and then concurrently sending off a new chunk into the bitmap when `values[i] % 2^16 != values[i+1] % 2^16`

**Comment by lemire** [comment]
@brentp  The optimized code is already there...
https://github.com/RoaringBitmap/CRoaring/blob/master/src/roaring.c#L93-L112

We just need to *move* it to a new function that would be part of the public API.

(Arguably, one could fine tune the code a bit so that it is clearer.)

**Comment by lemire** [comment]
If someone wants to have a go at this, please do so... We even have optimized code... so it is not a big implementation challenge. The hardest part would probably be to add sanity tests.

**Comment by lemire** [comment]
Partially satisfied with this commit

https://github.com/RoaringBitmap/CRoaring/commit/dd61a2a4265e8ab3c22574a3f587286f44c90762

**Comment by lemire** [comment]
It remains to implement a bulk remove function.

**Comment by lemire** [comment]
Since we have derived quite a bit, I will close this and open a new issue.
