### ISSUE TITLE
Add a subset test

### ISSUE THREAD

**Issue by Ezibenroc** [RoaringBitmap/CRoaring#55]
We can test if two bitmaps are equal, but we cannot test if one is included in the other.
This can be done by computing the intersection (or the union) of the two bitmaps, but I guess that this is not very efficient.

We should add two functions like this:

```c
// Return true if and only if ra1 ⊆ ra2
bool roaring_bitmap_included(roaring_bitmap_t *ra1, roaring_bitmap_t *ra2);
// Return true if and only if ra1 ⊊ ra2
bool roaring_bitmap_strictly_included(roaring_bitmap_t *ra1, roaring_bitmap_t *ra2);
```
We can easily compute one function with the other and `roaring_bitmap_equal`, but again this would not be very efficient.

**Comment by fsaintjacques** [comment]
Strict inclusion can be checked with inclusion + check on sizes, i.e. ra1.size < ra2.size.

**Comment by lemire** [comment]
@fsaintjacques  True but it could be faster to have one function call.

**Comment by lemire** [comment]
@fsaintjacques  Basically, you can already compute these things... for example, if  X ANDNOT Y is empty, then it follows that X must be contained in Y. The idea here would be to have a *faster* function. So I have added the performance tag.
