### ISSUE TITLE
Index returning methods?

### ISSUE THREAD

**Issue by mrboojum** [RoaringBitmap/CRoaring#58]
The roaring bitmaps have a constructor from a list of integer values and a query method for occurrence with a boolean result. This is great but I have a need for determining the indices/positions of the values in the original list matching a certain condition.
An example of such a method would be:
```
/**
Returns true if there is an entry in org equal to val (containing the original integer values),
and adds all the indices of the entries in org equal to val to the bitmap ind.
*/
inline bool roaring_bitmap_contains(const roaring_bitmap_t *org,
    roaring_bitmap_t *ind, uint32_t val);
```
Example test:
```
roaring_bitmap_t *org = roaring_bitmap_of(5, 1, 2, 3, 5, 6);
roaring_bitmap_t *ind = roaring_bitmap_create();
bool contains =roaring_bitmap_contains(org, ind, 5);
// ind should contain {0, 4}
uint32_t counter = 0;
roaring_iterate(org, roaring_iterator_sumall, &counter);
assert_true(counter == 2);
```
Other conditions for search would be larger/smaller/bitwise_or/bitwise_and. Ideally additional methods with a third bitmap parameter 'mask' indicating which bitmaps could be skipped would also be available. 

As the concept of (croaring) bitmaps is new to me, I'm wondering if such methods are perhaps already available or if its possible to construct them from the current available methods in roaring.h?
If this is not the case then I would like to know if there is intent to add them and with what priority? Perhaps such functionality is considered being out of the scope of this repository.

**Comment by Ezibenroc** [comment]
I am not sure to understand you well. In your example, you would like `ind` to be `{0,  4}` (i.e. the indicies of `5` in `org`)?

If so, I fear it is not possible. Roaring bitmaps represent sets of integers. A value is either in the set, or not, but there is no several instances. Moreover, we do not keep track of the indices of the value in the "original list" (a value may be added by another mean than a list, for instance by creating an empty bitmap and then adding all the values one by one).

Did I understand well?

**Comment by lemire** [comment]
@mrboojum 

I don't understand your function spec.

I don't understand your example.

**Comment by mrboojum** [comment]
Thanks for the reply, 
@Ezibenroc 
Yes I would like ind to be { 0, 4 }.
As I now read the implementation details in the paper better I understand why this not possible (I have interpreted the "adding all values one by one" method as adding to the list).
