### ISSUE TITLE
Implement ranged add/remove

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/CRoaring#59]
Add functions to remove or add all integers in an interval.

**Comment by Ezibenroc** [comment]
The add part could be quickly done by reformating the code from [`roaring_bitmap_from_range`](https://github.com/RoaringBitmap/CRoaring/blob/master/src/roaring.c#L136-L161) (same spirit as what you did for the `add_many` function).

**Comment by lemire** [comment]
@Ezibenroc  You are absolutely right.

**Comment by lemire** [comment]
Note that we have the related  ``roaring_bitmap_flip_inplace``.

**Comment by lemire** [comment]
This has been solved.
