### ISSUE TITLE
How to use `containsRange` in roaring64

### ISSUE THREAD

**Issue by MochiXu** [RoaringBitmap/CRoaring#597]
It seems that `roaring64` doesn't have function `containsRange`.
Could you please give me some suggestions about how to use `containsRange` in `roaring64`?
```cpp
  /**
   * Check if all values from x (included) to y (excluded) are present
   */
  bool containsRange(const uint64_t x, const uint64_t y) const noexcept {
      return api::roaring_bitmap_contains_range(&roaring, x, y);
  }
```

**Comment by SLieve** [comment]
`Roaring64Map` internally uses a `std::map` of `uint32_t` for the high 32 bits of values, to a 32-bit Roaring bitmap containing the low 32 bits of values with the associated high 32 bits. This means that using `roaring_bitmap_contains_range` will only determine whether a specific 32-bit Roaring bitmap contains a given 32-bit range.

To determine whether a 64-bit range is fully present in the `Roaring64Map`, we would need to loop over all different high 32 bits of the range, and check the corresponding 32-bit Roaring bitmaps for subranges. See a similar implementation [here](https://github.com/RoaringBitmap/CRoaring/blob/master/src/roaring64.c#L398) (that is the 64-bit C implementation, not the C++ implementation, I know it's confusing).

**Comment by MochiXu** [comment]
Is there a way to invert a `roaring::Roaring` bitmap entirely? For example, for `01001`, after inverting, it becomes `10110`. Currently, my method involves creating a `uint32` full bitmap and then subtracting the target bitmap from it to obtain the inverse of the target bitmap. However, I've found this operation to be quite inefficient, taking up nearly 450ms.

**Comment by SylvesterKwon** [comment]
Now we have `containsRange` and `containsRangeClosed` for `Roaring64Map` (#829).
