### ISSUE TITLE
Add a function to move the iterator to be equal or smaller than a value

### ISSUE THREAD

**Issue by xin-hedera** [RoaringBitmap/CRoaring#615]
The library supports `roaring_uint32_iterator_move_equalorlarger(roaring_uint32_iterator_t *, uint32_t)`, which can in turn support forward look up of a limited number of values in a range with really good performance. It's much needed to have a counterpart function, e.g., `roaring_uint32_iterator_move_equalorsmaller(roaring_uint32_iterator_t *, uint32_t)`, so the reverse lookup (given a range, find the largest X values in the roaring bitmap) can have the same level of performance.

**Comment by lemire** [comment]
Can't you use `roaring_uint32_iterator_previous`?

**Comment by xin-hedera** [comment]
> Can't you use `roaring_uint32_iterator_previous`?

I don’t think it can perform well given there are a large number of bits between the end of the range to search and the last value in the roaring bitmap. My assumption is by using that function, the implementation needs to iterates backwards from the last value.

**Comment by Dr-Emann** [comment]
I'd recommend a benchmark showing an unreasonable performance loss.

Keep in mind that Roaring bitmaps are compressed bitmaps, going back to the previous set bit will never have to do much work. For instance, in:

```c
roaring_bitmap_t *r = roaring_bitmap_from(1, UINT32_MAX);
roaring_uint32_iterator_t it;
roaring_iterator_init(r, &it);
roaring_uint32_iterator_move_equalorlarger(&it, 2); // Iterator points at UINT32_MAX
roaring_uint32_iterator_previous(&it);              // Iterator points at 1
```

both `roaring_uint32_iterator_move_equalorlarger` and `roaring_uint32_iterator_previous` will be _very_ quick, as the iterator is able to skip directly between the two values.

**Comment by lemire** [comment]
This being said, if you want to implement the desired functionality, a pull request would be given full consideration. It could lead to more elegant code.
