### ISSUE TITLE
access the nullptr in function "run_container_is_full" 

### ISSUE THREAD

**Issue by ZhCoding** [RoaringBitmap/CRoaring#626]
https://github.com/RoaringBitmap/CRoaring/blob/5b286605bdf53c2614bfb3155158ec761dce22b2/include/roaring/containers/run.h#L387

if we create an empty run container by "run_container_t *run_container_create(void);", and check it by "run_container_is_full", "runs" which is nullptr will be visited without checking.

**Comment by lemire** [comment]
The container should not be empty. If it is empty, you are in an invalid state.

>  "run_container_t *run_container_create(void);", and check it by "run_container_is_full", "runs" which is nullptr will be visited without checking.

That's not part of our public API. You are not supposed to create containers.

**Comment by ZhCoding** [comment]
> The container should not be empty. If it is empty, you are in an invalid state.
> 
> > "run_container_t *run_container_create(void);", and check it by "run_container_is_full", "runs" which is nullptr will be visited without checking.
> 
> That's not part of our public API. You are not supposed to create containers.

Which API files are considered public API?

**Comment by lemire** [comment]
Everything having to do with Roaring Bitmaps: https://github.com/RoaringBitmap/CRoaring/blob/master/include/roaring/roaring.h

**Comment by lemire** [comment]
This is explicit in the README, see section API:

<img width="890" alt="Screenshot 2024-05-12 at 7 02 34 PM" src="https://github.com/RoaringBitmap/CRoaring/assets/391987/55178322-9690-4e7d-9aae-184c34571a9e">

**Comment by lemire** [comment]
You can also go to our documentation site: http://roaringbitmap.github.io/CRoaring/
