### ISSUE TITLE
posix_memalign and free function caused crash.

### ISSUE THREAD

**Issue by jcai** [RoaringBitmap/CRoaring#63]
When I use mingw to compile CRoaring,I implemented posix_memalign .
```c
#ifdef __WIN32__
int posix_memalign(void** mem,size_t alignment,size_t size){
  *mem = _aligned_malloc(size,alignment);
  return 0;
}
#endif
```

But I found free function caused crash.

```c
/* Free memory. */
void bitset_container_free(bitset_container_t *bitset) {
    free(bitset->array);  // <==============   this line caused crash.
    bitset->array = NULL;
    free(bitset);
}
```

How to fix ? use _align_free function? I am not sure that all bitset->array was always allocated by posix_memalign function .

**Comment by lemire** [comment]
I think you are using an old release. We hopefully fixed this in our last release. Please upgrade to the latest version and let us know.

The latest unity build can be found at https://github.com/lemire/CRoaringUnityBuild

**Comment by lemire** [comment]
I am going to close this. Reopen if the problem persists after you upgraded to the latest version.

**Comment by jcai** [comment]
Thank you very much.When I upgrade to v0.2.7,all works well!

**Comment by lemire** [comment]
@RogueException : are you using v0.2.7 as well?

**Comment by RogueException** [comment]
0.2.7 fixed my bug as well, thanks @lemire.

**Comment by lemire** [comment]
Yes! Victory!
