### ISSUE TITLE
Release 4.1.1 amalgamation claims to be version 4.0.0

### ISSUE THREAD

**Issue by Dr-Emann** [RoaringBitmap/CRoaring#645]
The amalgamation h/hh/c files from the [newest release](https://github.com/RoaringBitmap/CRoaring/releases/tag/v4.1.1) appear to still be for version 4.0.0:

- https://github.com/RoaringBitmap/CRoaring/releases/download/v4.1.1/roaring.c
- https://github.com/RoaringBitmap/CRoaring/releases/download/v4.1.1/roaring.h
- https://github.com/RoaringBitmap/CRoaring/releases/download/v4.1.1/roaring.hh

Excerpts:

```c
// Created by amalgamation.sh on 2024-07-03T21:30:32Z
```

```c
#define ROARING_VERSION "4.0.0"
enum {
    ROARING_VERSION_MAJOR = 4,
    ROARING_VERSION_MINOR = 0,
    ROARING_VERSION_REVISION = 0
};
```

However, I see some (not all) of the changes since 4.0.0 in the contents.

**Comment by lemire** [comment]
???? I wonder how that happened.

**Comment by lemire** [comment]
Thanks for reporting the issue. Fixed.

**Comment by Dr-Emann** [comment]
@lemire Seems to have also happened similarly-ish to 4.1.0, just didn't notice: https://github.com/RoaringBitmap/croaring-rs/commit/6bf6d813be0e6814bb70d5f21520fa4dd3a44d6b#diff-2f754bb8d43e943c7fe002e45617ac8702980875d17f706ec1e4ca9dedb7cb80 - No update to the `ROARING_VERSION`

**Comment by lemire** [comment]
:-/

It won't happen in the future.

**Comment by lemire** [comment]
Updated 4.1.0.
