### ISSUE TITLE
Naming and initialization inconsistency in iterator APIs

### ISSUE THREAD

**Issue by cubicYYY** [RoaringBitmap/CRoaring#652]
Currently, the 32-bit version uses `RoaringSetBitForwardIterator` to implement **both** forward(operator `++`) and backward(operator `--`) iterator, while the 64-bit version uses `Roaring64MapSetBitBiDirectionalIterator`. The word "forward" in the name is a little bit confusing. Should the name be preserved for backward compatibility, or be changed for consistency?

Also, I observed that `roaring_iterator_init` is invoked in `begin()`, however `roaring_iterator_init_last` introduced in #190 is NOT invoked in `end()`. Instead, it `loadlastvalue()` when the iterator actually goes backward. Is this an intentional design?

I'm thinking about contributing. Thank you in advance.

**Comment by lemire** [comment]
> Should the name be preserved for backward compatibility, or be changed for consistency?

A name change seems reasonable although we may want to preserve the old name as well for backward compatibility with a [type alias](https://en.cppreference.com/w/cpp/language/type_alias).

> Is this an intentional design?

Updating code that use deprecated functions is useful.

> I'm thinking about contributing. Thank you in advance.

Pull request invited.

**Comment by lemire** [comment]
I am going to close this issue since it is not really an issue but rather a set of questions. Please note that there is a discussions tab in the project that can be used for such purposes.
