### ISSUE TITLE
Efficiently Solve Equation  A = B + C A=B+C with Roaring Bitmaps

### ISSUE THREAD

**Issue by frantoqui** [RoaringBitmap/CRoaring#685]
Hi,

I need guidance on how to efficiently solve the equation A = B + C using Roaring Bitmaps. Here’s the context:

- Known Inputs: 
  - A and B are Roaring Bitmap objects.
  - C is a variable (unknown bitmap) that needs to be determined.

- Challenges:
  1. The ranges I’m working with are very large, making it computationally expensive to iterate through all potential values of C.
  2. There are multiple combinations of A and B that yield the same result, introducing redundancies.
  3. Overflow handling is necessary when summing bitmap values.

Is there an efficient way to handle this problem within the Roaring Bitmap framework or using any related techniques to avoid exhaustive iteration?

Thank you in advance for any suggestions or pointers!

**Comment by Dr-Emann** [comment]
`+` isn't a clear operation. Do you mean union? Are you trying to find a (or all?) bitmap `C` which when unioned with `B` will yield `A`?

The minimal bitmap which satisfies that criteria can be `C = roaring_bitmap_andnot(A, B)`

**Comment by lemire** [comment]
I am going to close this. Please consider using the 'discussion' feature on GitHub instead of opening an issue.

Issues should be primarily about bugs, feature requests and the like.
