### ISSUE TITLE
cmake for -std=c11

### ISSUE THREAD

**Issue by rsharris** [RoaringBitmap/CRoaring#69]
One program a few people installing at our site had was that cmake apparently defaults to using cc instead of gcc, and our cc didn't support the -std=c11 flag. The solution was to add -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ to the cmake command line.

Is this problem common enough to make it worth adding a note about it in README.md's build instructions?

**Comment by lemire** [comment]
Resolved. Thanks.

https://github.com/RoaringBitmap/CRoaring/commit/12fc29c87c590daa57fab7c31c1db977a59d2d67
