### ISSUE TITLE
Loading from memory-mapped files + fast operations over serialized bitmaps

### ISSUE THREAD

**Issue by aaiyer** [RoaringBitmap/CRoaring#74]
Loading from memory-mapped files - this feature exists in the Java Roaring Bitmap library

**Comment by lemire** [comment]
Indeed.

**Comment by lemire** [comment]
This has been implemented in Go: https://github.com/RoaringBitmap/roaring . One useful insight is that we can use copy-on-write so that the resulting bitmaps can be safely modified even when the backing data is immutable.

**Comment by richardzhangrui** [comment]
@lemire Hi Lemire. Is this(fast operation over serialized bitmap) implemented in CRoaring now? Thanks.
