### ISSUE TITLE
Add support for dynamic libraries under Visual Studio

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/CRoaring#78]
Currently, we can build ``CRoaring`` as either a shared or static library (by default as a shared library, but static with ``BUILD_STATIC=ON``).

This works on posix systems (macOS and Linux) but for Visual Studio, we need to default on ``BUILD_STATIC=ON``. 

For Visual Studio to support dynamic libraries, we probably need extra code (e.g., ``__declspec(dllexport)`` calls?)

**Comment by lemire** [comment]
c.c. @ksajme

**Comment by madscientist** [comment]
Honestly, I'm not sure what the use-case is for a CRoaring DLL... would someone really want a sparse bitmap library as a DLL?

As you mention it is some extra work dealing with export etc.  If it were me I'd wait until someone actually wants it, before spending time on it.  But of course, YMMV! :)

**Comment by lemire** [comment]
@madscientist  I think it is useful to document that we do not support building a dynamic library under Visual Studio currently.

**Comment by madscientist** [comment]
@lemire  Agreed.  It's always better if these things aren't a surprise...

**Comment by KingJiangNet** [comment]
I have a wrapped it into a VS project: https://github.com/KingJiangNet/CRoaring.Net/tree/master/src/CRoaring

**Comment by lemire** [comment]
@KingJiangNet Right. So it would not be very difficult for us to integrate this into the main code.

**Comment by lemire** [comment]
Fixed in release 0.2.22.
