### ISSUE TITLE
library is thread-safe?

### ISSUE THREAD

**Issue by hxfxjun** [RoaringBitmap/CRoaring#90]
thread 1 add value to bitmap and thread 2 read value from bitmap?library is thread-safe?

**Comment by fsaintjacques** [comment]
It isn't.

**Comment by lemire** [comment]
@fsaintjacques  is of course correct. I have added some documentation to this effect...

https://github.com/RoaringBitmap/CRoaring#thread-safety

So I am going to close this. Reopen if you disagree.
