### ISSUE TITLE
library is thread-safe?

### ISSUE THREAD

**Issue by hxfxjun** [RoaringBitmap/CRoaring#91]
I write search program, want use RoaringBitmap to inverted index, only one thread update inverted and just use array_container_add append function(not used other function like roaring_bitmap_run_optimize) and doc_id is increment 1 each times and have many threads only read inverted index, and write thread used RCU technique and delay free memory !

# example code
```
roaring_bitmap_t * r1
roaring_bitmap_t * r2

write thread:
  for (int i = 0; i < MAX_INT32; i++) {
    roaring_bitmap_add(r1, i);
    roaring_bitmap_add(r2, i);
    usleep(10);
  }

read thread:
while(true) {
    r3 = roaring_bitmap_and(r1, r2);
   // do somethings
   usleep(10)
}

```

**Comment by lemire** [comment]
If you are calling ``roaring_bitmap_add`` on ``r1`` and ``r2`` while calling ``roaring_bitmap_and`` in another thread, then it is not safe.

If you need this kind of thread safety, then you have to implement it on your own as an extension.

I am closing this issue.
