### ISSUE TITLE
roaring_bitmap_copy api bug

### ISSUE THREAD

**Issue by hxfxjun** [RoaringBitmap/CRoaring#94]
if source bitmap is empty,call roaring_bitmap_copy is has carsh
```
bool ra_copy(const roaring_array_t *source, roaring_array_t *dest,
             bool copy_on_write) {
    if (!ra_init_with_capacity(dest, source->size)) return false;
```
if bitmap is empty source->size = 0 , and ra_init_with_capacity malloc size is 0
```
bool ra_init_with_capacity(roaring_array_t *new_ra, uint32_t cap) {
    void *bigalloc =
        malloc(cap * (sizeof(uint16_t) + sizeof(void *) + sizeof(uint8_t)));
```
modify
```
    if (!ra_init_with_capacity(dest, source->allocation_size)) return false;
```

**Comment by lemire** [comment]
Please provide a unit test to illustrate the bug as well as a complete rationale.

Your corresponding PR does not seem to fix an obvious bug:
https://github.com/RoaringBitmap/CRoaring/pull/95

> if bitmap is empty source->size = 0 , and ra_init_with_capacity malloc size is 0

Yes. The standard does allow malloc(0). It is safe.

**Comment by lemire** [comment]
Please see the following unit test (it passes): 

https://github.com/RoaringBitmap/CRoaring/commit/e1fbf259e8b6312e42f70fa8e97ab39cab62bab6

**Comment by lemire** [comment]
Closing since that is no follow up.

**Comment by lemire** [comment]
See https://github.com/RoaringBitmap/CRoaring/issues/101
