### ISSUE TITLE
Memory leak when reading RoaringBitMap from buffer (deserialize)

### ISSUE THREAD

**Issue by mariolg** [RoaringBitmap/CRoaring#96]
Hello,
I have a simple code, just to read a seralization of a Roaring64Map generated from a Go process (I enclose a .zip with the file) - btw I'm using amalgamation-:

```
#include <iostream>
#include <fcntl.h>
#include <unistd.h>
#include "roaring.hh"
#include "roaring.c"

#define  N   100*1024*1024

int main()
{
  char *buf = new char[N];
  int f = open("/tmp/goroar_small.bin", O_RDONLY, 0777);
  read(f, buf, N);
  close(f);

	Roaring64Map rbm = Roaring64Map::read(buf);
  delete[] buf;
                  
  return 0;
}
```

[goroar_small.zip](https://github.com/RoaringBitmap/CRoaring/files/963913/goroar_small.zip)

This code is compiled as follows (gcc versión 5.1.0 (GCC), Centos 7, but I think the error is independant from compiler):

```
#!/bin/bash

/opt/compiled/gcc-5.1.0/bin/g++    -Wall -Werror -DDISABLE_X64=ON -Wno-unknown-pragmas -Wno-unused-result -Wno-unused-but-set-variable -Wno-strict-aliasing -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -DHAVE_CDNCONFIG_H  -D_REENTRANT -fmessage-length=0 -fPIC -DNDEBUG -O3 -g3  -m64  -Ofast -ftree-loop-distribution -floop-parallelize-all -std=c++11 /tmp/main.cpp -o /tmp/main

chmod +x /tmp/main

/opt/compiled/gcc-5.1.0/bin/valgrind --leak-check=full /tmp/main
```

It will detect a memory leak due to in roaring.hh:385:

```
            Roaring ans;
            bool is_ok =
                ra_portable_deserialize(&ans.roaring.high_low_container, buf);
```

`ans` calls the constructor (roaring.hh:25):

```
    Roaring() {
        bool is_ok = ra_init(&roaring.high_low_container);
```

It reserves an initial capacity (roaring.c:9263) => malloc:

```
bool ra_init(roaring_array_t *t) {
    return ra_init_with_capacity(t, INITIAL_CAPACITY);
}
```

After `ans` is built, deserialization is called (`bool is_ok =             ra_portable_deserialize(&ans.roaring.high_low_container, buf);`) and inside it reserves with the capacity read from data in file (roaring.c:9723):,

` bool is_ok = ra_init_with_capacity(answer, size);`

My proposal, is to call `ra_clear(answer)` just before the init:

```
ra_clear(answer); //free initial capacity reservation
  bool is_ok = ra_init_with_capacity(answer, size);
```

May you please check and/or validate it?

Thanks in advance.
--Mario LG

**Comment by lemire** [comment]
Yes. There was a leak. I think it is fixed now in the latest release... See this commit.

https://github.com/RoaringBitmap/CRoaring/commit/bead863d198fd63b5b3d02b059f2d1354de58bcf

Reopen if the problem persists.
